package releasecontract

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/glade-sh/glade/tools/internal/surfaceledger"
)

var generatedVersionPaths = []string{
	"internal/apexversion/support_generated.go",
	"internal/sema/platform_availability_generated.go",
	"internal/lwc/compile/module_availability_generated.go",
	"internal/storage/rest_versions_generated.go",
	"internal/server/tooling_availability_generated.go",
}

// Generate writes or checks the compact Glade tables derived from an analyzed
// release contract. write=false is read-only and requires exact generated bytes.
func Generate(analysis Analysis, gladeRoot string, write bool) ([]string, error) {
	if analysis.Report.SurfaceDelta.Total != analysis.Report.SurfaceDelta.Classified ||
		analysis.Report.BehaviorDelta.Total != analysis.Report.BehaviorDelta.Classified ||
		analysis.Report.ChangeInventory.Total != analysis.Report.ChangeInventory.Routed ||
		len(analysis.Report.Unclassified) != 0 {
		return nil, fmt.Errorf("release contract is not fully classified and routed")
	}
	root, err := filepath.Abs(gladeRoot)
	if err != nil {
		return nil, err
	}
	if err := validateGladeRoot(root); err != nil {
		return nil, err
	}
	sources, err := renderGeneratedVersionSources(analysis)
	if err != nil {
		return nil, err
	}
	for _, relative := range generatedVersionPaths {
		path := filepath.Join(root, filepath.FromSlash(relative))
		want := sources[relative]
		if write {
			if err := writeGeneratedFile(path, want); err != nil {
				return nil, err
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("generated file drift: %s: %w", relative, err)
		}
		if !bytes.Equal(got, want) {
			return nil, fmt.Errorf("generated file drift: %s", relative)
		}
	}
	return append([]string(nil), generatedVersionPaths...), nil
}

func renderGeneratedVersionSources(analysis Analysis) (map[string][]byte, error) {
	manual := map[string]bool{}
	removed := map[string]bool{}
	unsupported := map[string]bool{}
	for _, change := range analysis.SurfaceChanges {
		key := surfaceledger.CanonicalSurfaceIDKey(change.Entry.SurfaceID)
		if change.Classification != nil && change.Classification.Disposition == surfaceledger.DispoExplicitUnsupported {
			unsupported[key] = true
		}
		switch change.Entry.Kind {
		case surfaceledger.DeltaChanged:
			manual[key] = true
		case surfaceledger.DeltaRemoved:
			removed[key] = true
		case surfaceledger.DeltaAdded:
			if removed[key] {
				manual[key] = true
			}
		}
	}
	bound := map[string]bool{}
	for _, behavior := range analysis.Contract.Behaviors {
		for _, id := range behavior.SurfaceIDs {
			bound[surfaceledger.CanonicalSurfaceIDKey(id)] = true
		}
	}
	for key := range manual {
		if unsupported[key] {
			continue
		}
		if !bound[key] {
			return nil, fmt.Errorf("manual surface %s requires a behavior surfaceId binding", key)
		}
	}

	typeRanges := map[string]Range{}
	exactRanges := map[string]Range{}
	memberCandidates := map[string]Range{}
	manualGroups := map[string]bool{}
	manualIDs := make([]string, 0, len(manual))
	unsupportedPlatformIDs := []string{}
	lwcRanges := map[string]Range{}
	toolingRanges := map[string]Range{}
	for _, change := range analysis.SurfaceChanges {
		row := change.Entry.New
		if row == nil {
			row = change.Entry.Old
		}
		if row == nil {
			return nil, fmt.Errorf("surface change %s has no row", change.Entry.SurfaceID)
		}
		key := surfaceledger.CanonicalSurfaceIDKey(change.Entry.SurfaceID)
		rng, ok := analysis.Report.Ranges[key]
		if !ok {
			return nil, fmt.Errorf("surface change %s has no range", change.Entry.SurfaceID)
		}
		if unsupported[key] {
			if row.Product == surfaceledger.ProductApex {
				unsupportedPlatformIDs = appendUnique(unsupportedPlatformIDs, key)
			}
			continue
		}
		if manual[key] {
			if row.Product == surfaceledger.ProductApex {
				manualIDs = appendUnique(manualIDs, key)
				if row.MemberName != "" {
					manualGroups[apexMemberKey(*row)] = true
				}
			}
			continue
		}
		if rangeAllowsAll(rng, analysis.Contract.Windows.Source) {
			continue
		}
		switch {
		case row.Product == surfaceledger.ProductApex && row.Kind == surfaceledger.KindType:
			key := strings.ToLower(strings.TrimSpace(row.Namespace + "." + row.TypeName))
			if key == "." {
				return nil, fmt.Errorf("Apex type %s has no namespace and type name", row.SurfaceID)
			}
			typeRanges[key] = rng
		case row.Product == surfaceledger.ProductApex && row.MemberName != "":
			exactRanges[key] = rng
			memberCandidates[apexMemberKey(*row)] = rng
		case row.Product == surfaceledger.ProductLWC && row.Kind == surfaceledger.KindModule:
			module, err := lwcModuleSpecifier(change.Entry.SurfaceID)
			if err != nil {
				return nil, err
			}
			lwcRanges[module] = rng
		case row.Product == surfaceledger.ProductTooling && row.Kind == surfaceledger.KindType:
			name := strings.TrimSpace(strings.TrimPrefix(change.Entry.SurfaceID, "tooling:"))
			if name == "" {
				return nil, fmt.Errorf("Tooling type %s has no object name", change.Entry.SurfaceID)
			}
			toolingRanges[name] = rng
		}
	}
	sort.Strings(manualIDs)
	sort.Strings(unsupportedPlatformIDs)

	memberRanges := map[string]Range{}
	for member, candidate := range memberCandidates {
		if manualGroups[member] || !allApexMemberRangesEqual(analysis.Report.Ranges, member, candidate) {
			continue
		}
		memberRanges[member] = candidate
	}

	sourceVersions := versionStrings(analysis.Contract.Windows.Source)
	endpointVersions := versionStrings(analysis.Contract.Windows.Endpoint)
	sources := map[string]string{
		generatedVersionPaths[0]: renderVersionList("apexversion", "DefaultSourceAPIVersion", analysis.Contract.Defaults.Source, "SupportedSourceAPIVersions", sourceVersions),
		generatedVersionPaths[1]: renderAvailability(typeRanges, memberRanges, exactRanges, manualIDs, unsupportedPlatformIDs),
		generatedVersionPaths[2]: renderLWCAvailability(lwcRanges),
		generatedVersionPaths[3]: renderVersionList("storage", "DefaultRESTAPIVersion", analysis.Contract.Defaults.Endpoint, "SupportedRESTAPIVersions", endpointVersions),
		generatedVersionPaths[4]: renderToolingAvailability(toolingRanges),
	}
	formatted := make(map[string][]byte, len(sources))
	for path, source := range sources {
		data, err := format.Source([]byte(source))
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", path, err)
		}
		formatted[path] = data
	}
	return formatted, nil
}

func apexMemberKey(row surfaceledger.SurfaceLedgerRow) string {
	return strings.ToLower(strings.TrimSpace(row.Namespace + "." + row.TypeName + "." + row.MemberName))
}

func allApexMemberRangesEqual(ranges map[string]Range, member string, want Range) bool {
	base := "apex:" + member
	found := false
	for id, rng := range ranges {
		if id != base && !strings.HasPrefix(id, base+"(") {
			continue
		}
		found = true
		if rng != want {
			return false
		}
	}
	return found
}

func rangeAllowsAll(rng Range, versions []VersionProof) bool {
	if len(versions) == 0 {
		return false
	}
	min, max := apiInt(versions[0].Version), apiInt(versions[0].Version)
	for _, version := range versions[1:] {
		major := apiInt(version.Version)
		if major < min {
			min = major
		}
		if major > max {
			max = major
		}
	}
	return rng.Since <= min && (rng.Until == 0 || rng.Until > max)
}

func lwcModuleSpecifier(surfaceID string) (string, error) {
	module := strings.TrimSpace(strings.TrimPrefix(surfaceID, "lwc:"))
	if len(module) >= 2 && module[0] == '`' && module[len(module)-1] == '`' {
		module = module[1 : len(module)-1]
	}
	if module == "" || strings.ContainsRune(module, '`') {
		return "", fmt.Errorf("invalid LWC module surfaceId %q", surfaceID)
	}
	return module, nil
}

func renderVersionList(pkg, defaultName, defaultVersion, listName string, versions []string) string {
	return generatedHeader(pkg) + "const " + defaultName + " = " + strconv.Quote(defaultVersion) + "\n\nvar " + listName + " = " + renderStrings(versions) + "\n"
}

func renderAvailability(types, members, exact map[string]Range, manual, unsupported []string) string {
	var b strings.Builder
	b.WriteString(generatedHeader("sema"))
	b.WriteString("import \"github.com/glade-sh/glade/internal/apexversion\"\n\n")
	renderRangeMap(&b, "generatedPlatformTypeAvailability", types)
	renderRangeMap(&b, "generatedPlatformMemberAvailability", members)
	renderRangeMap(&b, "generatedPlatformExactAvailability", exact)
	b.WriteString("var generatedManualSurfaceIDs = ")
	b.WriteString(renderStrings(manual))
	b.WriteByte('\n')
	b.WriteString("var generatedUnsupportedPlatformSurfaceIDs = ")
	b.WriteString(renderStrings(unsupported))
	b.WriteByte('\n')
	return b.String()
}

func renderLWCAvailability(modules map[string]Range) string {
	var b strings.Builder
	b.WriteString(generatedHeader("compile"))
	b.WriteString("import \"github.com/glade-sh/glade/internal/apexversion\"\n\n")
	renderRangeMap(&b, "generatedLWCModuleAvailability", modules)
	return b.String()
}

func renderToolingAvailability(objects map[string]Range) string {
	var b strings.Builder
	b.WriteString(generatedHeader("server"))
	b.WriteString("import \"github.com/glade-sh/glade/internal/apexversion\"\n\n")
	renderRangeMap(&b, "generatedToolingObjectAvailability", objects)
	return b.String()
}

func generatedHeader(pkg string) string {
	return "// Code generated by glade-tools salesforce release; DO NOT EDIT.\n\npackage " + pkg + "\n\n"
}

func renderRangeMap(b *strings.Builder, name string, values map[string]Range) {
	b.WriteString("var ")
	b.WriteString(name)
	b.WriteString(" = map[string]apexversion.Range{\n")
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		b.WriteByte('\t')
		b.WriteString(strconv.Quote(key))
		b.WriteString(": {")
		fields := []string{}
		if values[key].Since != 0 {
			fields = append(fields, fmt.Sprintf("Since: %d", values[key].Since))
		}
		if values[key].Until != 0 {
			fields = append(fields, fmt.Sprintf("Until: %d", values[key].Until))
		}
		b.WriteString(strings.Join(fields, ", "))
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
}

func renderStrings(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = strconv.Quote(value)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func appendUnique(values []string, value string) []string {
	for _, existing := range values {
		if existing == value {
			return values
		}
	}
	return append(values, value)
}

func validateGladeRoot(root string) error {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return fmt.Errorf("invalid Glade root: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) > 0 && fields[0] == "module" {
			if len(fields) == 2 && fields[1] == "github.com/glade-sh/glade" {
				return nil
			}
			break
		}
	}
	return fmt.Errorf("invalid Glade root: go.mod module must be github.com/glade-sh/glade")
}

func writeGeneratedFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+"-*.tmp")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return err
	}
	return nil
}
