package releasecontract

import (
	"go/format"
	"os"
	"path/filepath"
	"testing"

	"github.com/glade-sh/glade/tools/internal/surfaceledger"
)

func TestGenerateVersionTables(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module github.com/glade-sh/glade\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	row := func(id, product, kind, namespace, typeName, memberName string) surfaceledger.SurfaceLedgerRow {
		return surfaceledger.SurfaceLedgerRow{SurfaceID: id, Product: product, Kind: kind, Namespace: namespace, TypeName: typeName, MemberName: memberName}
	}
	change := func(kind surfaceledger.DeltaKind, r surfaceledger.SurfaceLedgerRow) SurfaceChange {
		entry := surfaceledger.DeltaEntry{SurfaceID: r.SurfaceID, Kind: kind}
		if kind == surfaceledger.DeltaRemoved {
			entry.Old = &r
		} else {
			entry.New = &r
		}
		return SurfaceChange{Entry: entry}
	}
	unsupported := change(surfaceledger.DeltaAdded, row("apex:System.Preview", surfaceledger.ProductApex, surfaceledger.KindType, "System", "Preview", ""))
	unsupported.Classification = &surfaceledger.ReleaseClassification{
		SurfaceID:   "apex:System.Preview",
		Scope:       surfaceledger.ScopeOutsideClaim,
		Disposition: surfaceledger.DispoExplicitUnsupported,
		ReasonRef:   "preview",
	}
	analysis := Analysis{
		Contract: Contract{
			Defaults: Defaults{Source: "65.0", Endpoint: "65.0"},
			Windows: Windows{
				Source:   []VersionProof{{Version: "65.0"}, {Version: "66.0"}, {Version: "67.0"}},
				Endpoint: []VersionProof{{Version: "60.0"}, {Version: "65.0"}, {Version: "66.0"}, {Version: "67.0"}},
			},
			Behaviors: []Behavior{{ID: "manual", SurfaceIDs: []string{"apex:Foo.NewType.changed()"}}},
		},
		Report: Report{
			SurfaceDelta:    Denominator{Total: 9, Classified: 9},
			BehaviorDelta:   Denominator{Total: 1, Classified: 1},
			ChangeInventory: ChangeInventoryDenominator{Total: 1, Routed: 1},
			Ranges: map[string]Range{
				"apex:foo.stable":                  {Since: 65},
				"apex:foo.newtype":                 {Since: 66},
				"apex:foo.newtype.value":           {Since: 67},
				"apex:foo.newtype.old()":           {Since: 65, Until: 67},
				"apex:foo.newtype.run(string)":     {Since: 66},
				"apex:foo.newtype.run(integer)":    {Since: 67},
				"apex:foo.newtype.changed()":       {Since: 65},
				"lwc:`experience/blockBuilderApi`": {Since: 66},
				"tooling:NewObject":                {Since: 67},
				"apex:system.preview":              {Since: 67},
			},
		},
		SurfaceChanges: []SurfaceChange{
			change(surfaceledger.DeltaAdded, row("apex:Foo.NewType", surfaceledger.ProductApex, surfaceledger.KindType, "Foo", "NewType", "")),
			change(surfaceledger.DeltaAdded, row("apex:Foo.NewType.value", surfaceledger.ProductApex, surfaceledger.KindProperty, "Foo", "NewType", "value")),
			change(surfaceledger.DeltaRemoved, row("apex:Foo.NewType.old()", surfaceledger.ProductApex, surfaceledger.KindMethod, "Foo", "NewType", "old")),
			change(surfaceledger.DeltaAdded, row("apex:Foo.NewType.run(String)", surfaceledger.ProductApex, surfaceledger.KindMethod, "Foo", "NewType", "run")),
			change(surfaceledger.DeltaAdded, row("apex:Foo.NewType.run(Integer)", surfaceledger.ProductApex, surfaceledger.KindMethod, "Foo", "NewType", "run")),
			change(surfaceledger.DeltaChanged, row("apex:Foo.NewType.changed()", surfaceledger.ProductApex, surfaceledger.KindMethod, "Foo", "NewType", "changed")),
			change(surfaceledger.DeltaAdded, row("lwc:`experience/blockBuilderApi`", surfaceledger.ProductLWC, surfaceledger.KindModule, "", "", "")),
			change(surfaceledger.DeltaAdded, row("tooling:NewObject", surfaceledger.ProductTooling, surfaceledger.KindType, "", "", "")),
			unsupported,
		},
	}

	paths, err := Generate(analysis, root, true)
	if err != nil {
		t.Fatalf("Generate write: %v", err)
	}
	if len(paths) != 5 {
		t.Fatalf("generated paths = %v", paths)
	}
	want := map[string]string{
		"internal/apexversion/support_generated.go": `// Code generated by glade-tools salesforce release; DO NOT EDIT.

package apexversion

const DefaultSourceAPIVersion = "65.0"

var SupportedSourceAPIVersions = []string{"65.0", "66.0", "67.0"}
`,
		"internal/storage/rest_versions_generated.go": `// Code generated by glade-tools salesforce release; DO NOT EDIT.

package storage

const DefaultRESTAPIVersion = "65.0"

var SupportedRESTAPIVersions = []string{"60.0", "65.0", "66.0", "67.0"}
`,
		"internal/server/tooling_availability_generated.go": `// Code generated by glade-tools salesforce release; DO NOT EDIT.

package server

import "github.com/glade-sh/glade/internal/apexversion"

var generatedToolingObjectAvailability = map[string]apexversion.Range{
	"NewObject": {Since: 67},
}
`,
		"internal/sema/platform_availability_generated.go": `// Code generated by glade-tools salesforce release; DO NOT EDIT.

package sema

import "github.com/glade-sh/glade/internal/apexversion"

var generatedPlatformTypeAvailability = map[string]apexversion.Range{
	"foo.newtype": {Since: 66},
}
var generatedPlatformMemberAvailability = map[string]apexversion.Range{
	"foo.newtype.old": {Since: 65, Until: 67},
	"foo.newtype.value": {Since: 67},
}
var generatedPlatformExactAvailability = map[string]apexversion.Range{
	"apex:foo.newtype.old()": {Since: 65, Until: 67},
	"apex:foo.newtype.run(integer)": {Since: 67},
	"apex:foo.newtype.run(string)": {Since: 66},
	"apex:foo.newtype.value": {Since: 67},
}
var generatedManualSurfaceIDs = []string{"apex:foo.newtype.changed()"}
var generatedUnsupportedPlatformSurfaceIDs = []string{"apex:system.preview"}
`,
		"internal/lwc/compile/module_availability_generated.go": `// Code generated by glade-tools salesforce release; DO NOT EDIT.

package compile

import "github.com/glade-sh/glade/internal/apexversion"

var generatedLWCModuleAvailability = map[string]apexversion.Range{
	"experience/blockBuilderApi": {Since: 66},
}
`,
	}
	for path, source := range want {
		formatted, err := format.Source([]byte(source))
		if err != nil {
			t.Fatalf("format expected %s: %v", path, err)
		}
		got, err := os.ReadFile(filepath.Join(root, path))
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != string(formatted) {
			t.Fatalf("%s:\n%s\nwant:\n%s", path, got, formatted)
		}
	}
	if _, err := Generate(analysis, root, false); err != nil {
		t.Fatalf("Generate check: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "internal/apexversion/support_generated.go"), []byte("drift\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := Generate(analysis, root, false); err == nil {
		t.Fatal("Generate check unexpectedly accepted drift")
	}
}
