package capability

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
)

type StdlibEntry struct {
	Area   string `json:"area"`
	API    string `json:"api"`
	Status Status `json:"status"`
	Notes  string `json:"notes,omitempty"`
}

func StdlibMatrix() []StdlibEntry {
	entries := append([]StdlibEntry(nil), stdlibEntries...)
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Area == entries[j].Area {
			return entries[i].API < entries[j].API
		}
		return entries[i].Area < entries[j].Area
	})
	return entries
}

func WriteStdlibJSON(w io.Writer) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(StdlibMatrix())
}

func WriteStdlibMarkdown(w io.Writer) error {
	if _, err := fmt.Fprintln(w, "# Standard Library Coverage"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\nGenerated from the first-party compat plugin capability catalog."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\nStatus values match the compatibility dashboard: `supported`, `partial`, `stub`, `unsupported`, and `unknown`."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\n| Area | API | Status | Notes |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| --- | --- | --- | --- |"); err != nil {
		return err
	}
	for _, entry := range StdlibMatrix() {
		if _, err := fmt.Fprintf(w, "| %s | `%s` | `%s` | %s |\n", entry.Area, entry.API, entry.Status, entry.Notes); err != nil {
			return err
		}
	}
	return nil
}

var stdlibEntries = []StdlibEntry{
	{Area: "AccessLevel", API: "AccessLevel.withPermissionSetId(String)", Status: StatusSupported, Notes: "Creates a local permission-set-scoped user-mode token used by supported SOQL and DML permission checks."},
	{Area: "Answers", API: "Answers.findSimilar(Question)", Status: StatusUnsupported, Notes: "Zone similar-question search requires Answers service data and returns a stable UnsupportedFeature diagnostic locally."},
	{Area: "ApexPages", API: "ApexPages.addMessage", Status: StatusSupported, Notes: "Stores page messages on the VM instance."},
	{Area: "ApexPages", API: "ApexPages.addMessage(ApexPages.Message)", Status: StatusSupported, Notes: "Stores page messages on the VM instance."},
	{Area: "ApexPages", API: "ApexPages.addMessages(Exception)", Status: StatusSupported, Notes: "Converts supported exception values into VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.addMessages(Object)", Status: StatusSupported, Notes: "Converts supported exception and message values into VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.currentPage", Status: StatusSupported, Notes: "Returns a deterministic local PageReference."},
	{Area: "ApexPages", API: "ApexPages.currentPage()", Status: StatusSupported, Notes: "Returns the VM-local PageReference."},
	{Area: "ApexPages", API: "ApexPages.getMessages", Status: StatusSupported, Notes: "Returns VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.getMessages()", Status: StatusSupported, Notes: "Returns VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.hasMessages", Status: StatusSupported, Notes: "Checks VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.hasMessages()", Status: StatusSupported, Notes: "Checks VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.hasMessages(ApexPages.Severity)", Status: StatusSupported, Notes: "Checks VM-local page messages by severity."},
	{Area: "ApexPages", API: "ApexPages.Message", Status: StatusPartial, Notes: "Constructor, getters, add/get/has message state, and Visualforce action reset behavior; no full rendering lifecycle."},
	{Area: "Boolean", API: "Boolean.valueOf(Object)", Status: StatusSupported, Notes: "Converts supported local field/object values into Boolean values."},
	{Area: "Boolean", API: "Boolean.valueOf(String)", Status: StatusSupported, Notes: "Converts strings to Boolean using Apex-shaped true/false parsing."},
	{Area: "Assert", API: "Assert.areEqual", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.areNotEqual", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.fail", Status: StatusSupported, Notes: "Raises local System.AssertException with optional message text."},
	{Area: "Assert", API: "Assert.isFalse", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.isNotNull", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.isNull", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.isTrue", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Approval", API: "Approval.process(Approval.ProcessRequest)", Status: StatusPartial, Notes: "Deterministic local approval result DTOs for submit/workitem request shapes; no live approval engine routing."},
	{Area: "Approval", API: "Approval.process(Approval.ProcessRequest, Boolean)", Status: StatusPartial, Notes: "Deterministic local approval result DTOs for submit/workitem request shapes; no live approval engine routing."},
	{Area: "BusinessHours", API: "BusinessHours.add(String, Datetime, Long)", Status: StatusPartial, Notes: "Local BusinessHours record-backed week schedule math; holiday and service-calendar edge behavior is not modeled."},
	{Area: "BusinessHours", API: "BusinessHours.addGmt(String, Datetime, Long)", Status: StatusPartial, Notes: "Local BusinessHours record-backed week schedule math; holiday and service-calendar edge behavior is not modeled."},
	{Area: "BusinessHours", API: "BusinessHours.diff(String, Datetime, Datetime)", Status: StatusPartial, Notes: "Local BusinessHours record-backed week schedule math; holiday and service-calendar edge behavior is not modeled."},
	{Area: "BusinessHours", API: "BusinessHours.isWithin(String, Datetime)", Status: StatusPartial, Notes: "Local BusinessHours record-backed week schedule math; holiday and service-calendar edge behavior is not modeled."},
	{Area: "BusinessHours", API: "BusinessHours.nextStartDate(String, Datetime)", Status: StatusPartial, Notes: "Local BusinessHours record-backed week schedule math; holiday and service-calendar edge behavior is not modeled."},
	{Area: "Crypto", API: "Crypto.generateDigest", Status: StatusPartial, Notes: "MD5, SHA-1/SHA1, SHA-256/SHA256, SHA-384/SHA384, SHA-512/SHA512, and SHA3-256/384/512 are modeled; unsupported digest names raise local SecurityException."},
	{Area: "Database", API: "Database.countQuery", Status: StatusSupported, Notes: "Dynamic SOQL count execution against the local org with local AccessLevel parsing."},
	{Area: "Database", API: "Database.convertLead", Status: StatusSupported, Notes: "Local lead conversion creates Account, Contact, and optional Opportunity records and updates Lead conversion fields."},
	{Area: "Database", API: "Database.delete", Status: StatusSupported, Notes: "DML pipeline with result/error shapes and local AccessLevel parsing for supported SObjects."},
	{Area: "Database", API: "Database.deleteAsync", Status: StatusSupported, Notes: "Local async delete alias runs through the DML pipeline and returns DeleteResult shape."},
	{Area: "Database", API: "Database.deleteImmediate", Status: StatusSupported, Notes: "Local immediate delete alias runs through the DML pipeline and returns DeleteResult shape."},
	{Area: "Database", API: "Database.countQueryWithBinds", Status: StatusSupported, Notes: "Bind-map dynamic SOQL count execution with local AccessLevel parsing."},
	{Area: "Database", API: "Database.emptyRecycleBin", Status: StatusSupported, Notes: "Local hard-delete result shape with allOrNone rollback for supported SObjects."},
	{Area: "Database", API: "Database.executeBatch", Status: StatusSupported, Notes: "Queues local Batchable jobs and drains start/execute chunks/finish during Test.stopTest."},
	{Area: "Database", API: "Database.getAsyncLocator", Status: StatusSupported, Notes: "Returns deterministic VM-local locator strings for local result and locator objects; no external async service lookup."},
	{Area: "Database", API: "Database.getAsyncDeleteResult", Status: StatusSupported, Notes: "Returns materialized local DeleteResult values and rejects unknown async locator strings instead of fabricating pending results."},
	{Area: "Database", API: "Database.getAsyncSaveResult", Status: StatusSupported, Notes: "Returns materialized local SaveResult values and rejects unknown async locator strings instead of fabricating pending results."},
	{Area: "Database", API: "Database.getCursor", Status: StatusSupported, Notes: "Local cursor over supported SOQL results with deterministic fetch windows."},
	{Area: "Database", API: "Database.getCursorWithBinds", Status: StatusSupported, Notes: "Bind-map local cursor over supported SOQL results with deterministic fetch windows."},
	{Area: "Database", API: "Database.getDeleted", Status: StatusSupported, Notes: "Returns local soft-deleted record tombstones whose deletion timestamp falls within the requested sync window."},
	{Area: "Database", API: "Database.getQueryLocator", Status: StatusSupported, Notes: "Supported SOQL executes eagerly for local batch scopes with local AccessLevel parsing."},
	{Area: "Database", API: "Database.getQueryLocatorWithBinds", Status: StatusSupported, Notes: "Bind-map dynamic SOQL locator execution with iterable local query locators."},
	{Area: "Database", API: "Database.getPaginationCursor", Status: StatusSupported, Notes: "Local pagination cursor over supported SOQL results with deterministic fetch windows."},
	{Area: "Database", API: "Database.getPaginationCursorWithBinds", Status: StatusSupported, Notes: "Bind-map local pagination cursor over supported SOQL results with deterministic fetch windows."},
	{Area: "Database", API: "Database.getUpdated", Status: StatusSupported, Notes: "Returns local record IDs whose system-modified timestamp falls within the requested sync window."},
	{Area: "Database", API: "Database.insert", Status: StatusSupported, Notes: "DML pipeline with result/error shapes and local AccessLevel parsing for supported SObjects."},
	{Area: "Database", API: "Database.insertAsync", Status: StatusSupported, Notes: "Local async insert alias runs through the DML pipeline and returns SaveResult shape."},
	{Area: "Database", API: "Database.insertImmediate", Status: StatusSupported, Notes: "Local immediate insert alias runs through the DML pipeline and returns SaveResult shape."},
	{Area: "Database", API: "Database.lock", Status: StatusSupported, Notes: "Local row-lock result shape with allOrNone rollback for supported SObjects."},
	{Area: "Database", API: "Database.merge", Status: StatusSupported, Notes: "Local merge behavior with result shape and AccessLevel parsing for supported schema-backed data."},
	{Area: "Database", API: "Database.query", Status: StatusSupported, Notes: "Dynamic SOQL execution against the local org with catchable QueryException parse errors."},
	{Area: "Database", API: "Database.queryWithBinds", Status: StatusSupported, Notes: "Bind-map dynamic SOQL execution with scalar and collection binds."},
	{Area: "Database", API: "Database.releaseSavepoint", Status: StatusSupported, Notes: "Releases the selected local savepoint and later savepoints without rolling back org state."},
	{Area: "Database", API: "Database.rollback", Status: StatusSupported, Notes: "Local org-state savepoint rollback with no external side effects."},
	{Area: "Database", API: "Database.setSavepoint", Status: StatusSupported, Notes: "Local org-state snapshots with later-savepoint invalidation."},
	{Area: "Database", API: "Database.treeSave", Status: StatusSupported, Notes: "Local parent insert/update plus first-level child insert/update with NestedSaveResult relationship result shape."},
	{Area: "Database", API: "Database.UnitOfWork", Status: StatusSupported, Notes: "Queues local DML operations and applies them on commitWork; discardWork drops pending local work."},
	{Area: "Database", API: "Database.undelete", Status: StatusSupported, Notes: "Soft-delete restoration with local AccessLevel parsing for supported local records."},
	{Area: "Database", API: "Database.unlock", Status: StatusSupported, Notes: "Local row-unlock result shape with allOrNone rollback for supported SObjects."},
	{Area: "Database", API: "Database.update", Status: StatusSupported, Notes: "DML pipeline with result/error shapes and local AccessLevel parsing for supported SObjects."},
	{Area: "Database", API: "Database.updateAsync", Status: StatusSupported, Notes: "Local async update alias runs through the DML pipeline and returns SaveResult shape."},
	{Area: "Database", API: "Database.updateImmediate", Status: StatusSupported, Notes: "Local immediate update alias runs through the DML pipeline and returns SaveResult shape."},
	{Area: "Database", API: "Database.upsert", Status: StatusSupported, Notes: "Schema-backed external-ID matching with local AccessLevel parsing for supported local records."},
	{Area: "Date", API: "Date.addMonths", Status: StatusSupported, Notes: "Local Gregorian month arithmetic with end-of-month clamping."},
	{Area: "Date", API: "Date.addYears", Status: StatusSupported, Notes: "Local Gregorian year arithmetic with leap-day clamping."},
	{Area: "Date", API: "Date.addDays", Status: StatusSupported, Notes: "Local Gregorian day arithmetic."},
	{Area: "Date", API: "Date.newInstance", Status: StatusSupported, Notes: "Validates date parts."},
	{Area: "Date", API: "Date.today", Status: StatusSupported, Notes: "Returns the deterministic local runtime date."},
	{Area: "Date", API: "Date.valueOf", Status: StatusSupported, Notes: "Parses supported date strings."},
	{Area: "Datetime", API: "Datetime.addDays", Status: StatusSupported, Notes: "UTC-local day arithmetic."},
	{Area: "Datetime", API: "Datetime.addHours", Status: StatusSupported, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addMinutes", Status: StatusSupported, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addMonths", Status: StatusSupported, Notes: "UTC-local month arithmetic with end-of-month clamping."},
	{Area: "Datetime", API: "Datetime.addSeconds", Status: StatusSupported, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addYears", Status: StatusSupported, Notes: "UTC-local year arithmetic with leap-day clamping."},
	{Area: "Datetime", API: "Datetime.format", Status: StatusSupported, Notes: "Formats using the deterministic local timezone model."},
	{Area: "Datetime", API: "Datetime.formatGmt", Status: StatusSupported, Notes: "Formats using GMT."},
	{Area: "Datetime", API: "Datetime.newInstance", Status: StatusSupported, Notes: "Validates date and time parts."},
	{Area: "Datetime", API: "Datetime.now", Status: StatusSupported, Notes: "Returns the deterministic local runtime datetime."},
	{Area: "Datetime", API: "Datetime.valueOf", Status: StatusSupported, Notes: "Parses supported datetime strings."},
	{Area: "Decimal", API: "Decimal.divide(Decimal,Integer,RoundingMode)", Status: StatusSupported, Notes: "Divides local Decimal values with explicit scale and RoundingMode."},
	{Area: "Decimal", API: "Decimal.doubleValue", Status: StatusSupported, Notes: "Returns local Decimal value."},
	{Area: "Decimal", API: "Decimal.intValue", Status: StatusSupported, Notes: "Truncates to integer."},
	{Area: "Decimal", API: "Decimal.round", Status: StatusPartial, Notes: "Uses deterministic local HALF_UP tie behavior for finite local Decimal values; full Salesforce Decimal precision is not modeled."},
	{Area: "Decimal", API: "Decimal.setScale", Status: StatusPartial, Notes: "Models finite local Decimal values, negative scale, and common RoundingMode ties up to the local scale fence; full Salesforce Decimal precision is not modeled."},
	{Area: "EncodingUtil", API: "EncodingUtil.base64Decode", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.base64Encode", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.convertFromHex", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.convertToHex", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.urlDecode", Status: StatusPartial, Notes: "Models URL form decoding for UTF-8, US-ASCII, and ISO-8859-1 aliases; broader Salesforce charset replacement behavior is not modeled."},
	{Area: "EncodingUtil", API: "EncodingUtil.urlEncode", Status: StatusPartial, Notes: "Models URL form encoding for UTF-8, US-ASCII, and ISO-8859-1 aliases with strict local charset checks; broader Salesforce charset replacement behavior is not modeled."},
	{Area: "Exception", API: "InvalidParameterValueException constructors", Status: StatusSupported, Notes: "Supports zero-arg, message, cause, and existing platform-specific constructor shapes."},
	{Area: "Exception", API: "NoAccessException constructors", Status: StatusSupported, Notes: "Supports zero-arg, message, cause, and message-plus-cause constructor shapes."},
	{Area: "Exception", API: "NoDataFoundException constructors", Status: StatusSupported, Notes: "Supports zero-arg, message, cause, and message-plus-cause constructor shapes."},
	{Area: "Exception", API: "NullPointerException constructors", Status: StatusSupported, Notes: "Supports zero-arg, message, cause, and message-plus-cause constructor shapes."},
	{Area: "FeatureManagement", API: "FeatureManagement.checkPermission", Status: StatusPartial, Notes: "Checks local runAs permission-list state."},
	{Area: "HTTP", API: "Http.send(HttpRequest)", Status: StatusSupported, Notes: "Routes local callouts through registered HttpCalloutMock implementations; real outbound network transport is intentionally not executed by the local runtime."},
	{Area: "HTTP", API: "HttpRequest", Status: StatusPartial, Notes: "Endpoint, method, headers, timeout, body, and blob body accessors."},
	{Area: "HTTP", API: "HttpResponse", Status: StatusPartial, Notes: "Status, status code, headers, body, and blob body accessors."},
	{Area: "JSON", API: "JSON.deserialize", Status: StatusPartial, Notes: "SObject, class, inner DTO, enum, collection, primitive, and string-key map shapes for supported targets; unsupported map key targets remain fenced."},
	{Area: "JSON", API: "JSON.deserializeStrict", Status: StatusPartial, Notes: "Rejects unknown fields for supported schema/class targets, including nested local DTO fields; unsupported target coercions remain outside the local model."},
	{Area: "JSON", API: "JSON.deserializeUntyped", Status: StatusPartial, Notes: "Maps JSON into local primitive/list/map values with deterministic Apex-shaped containers; full Salesforce parser edge parity is not modeled."},
	{Area: "JSON", API: "JSON.serialize", Status: StatusPartial, Notes: "Serializes supported Apex DTO, enum, SObject, collection, primitive, and suppressApexObjectNulls values; full Salesforce generator edge parity is not modeled."},
	{Area: "JSON", API: "JSON.serializePretty", Status: StatusPartial, Notes: "Pretty output for supported Apex DTO, SObject, collection, and primitive values; full Salesforce generator edge parity is not modeled."},
	{Area: "Label", API: "Label.get(String,String)", Status: StatusSupported, Notes: "Resolves local custom label metadata with existing platform and managed-namespace fallbacks."},
	{Area: "Label", API: "Label.get(String,String,String)", Status: StatusSupported, Notes: "Resolves local custom label metadata for an explicit language, then falls back to the local label resolver."},
	{Area: "Label", API: "Label.translationExists(String,String,String)", Status: StatusSupported, Notes: "Returns true when local label metadata has a matching explicit language translation."},
	{Area: "Limits", API: "Limits.get*", Status: StatusPartial, Notes: "SOQL, SOSL, DML, heap, CPU, async, callout, email, runAs, and savepoint counters are modeled; unmodeled getter families remain local defaults."},
	{Area: "Limits", API: "Limits.getAsyncCalls", Status: StatusSupported, Notes: "Returns the local async-call counter."},
	{Area: "Limits", API: "Limits.getLimitAsyncCalls", Status: StatusSupported, Notes: "Returns the local async-call limit."},
	{Area: "Math", API: "Math.abs", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.ceil", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.floor", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.max", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.min", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.pow", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.round", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.sqrt", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Messaging", API: "Messaging.SingleEmailMessage", Status: StatusPartial, Notes: "Common DTO setters/getters and local file attachments are modeled; no delivery transport or Salesforce content attachment service."},
	{Area: "Messaging", API: "Messaging.sendEmail", Status: StatusPartial, Notes: "Returns local SendEmailResult values, validates supported DTOs, and increments email limits; no delivery transport or send-options overloads."},
	{Area: "Messaging", API: "Messaging.sendEmail(Messaging.Email[],Boolean)", Status: StatusSupported, Notes: "Returns ordered local SendEmailResult values for supported email message DTOs; no delivery transport."},
	{Area: "Messaging", API: "Messaging.renderStoredEmailTemplate(String,String,String,Messaging.AttachmentRetrievalOption)", Status: StatusPartial, Notes: "Uses local stored-template rendering and static-resource attachment retrieval for METADATA_ONLY/METADATA_WITH_BODY; Salesforce content attachment relationships are not modeled."},
	{Area: "Messaging", API: "Messaging.renderStoredEmailTemplate(String,String,String,Messaging.AttachmentRetrievalOption,Boolean)", Status: StatusPartial, Notes: "Uses local stored-template rendering and static-resource attachment retrieval; updateEmailTemplateUsage is accepted for shape and ignored locally."},
	{Area: "PageReference", API: "PageReference", Status: StatusPartial, Notes: "Constructor, URL, redirect, mutable parameters, headers, and current-page state; getContent, PDF, and full rendering remain outside the local model."},
	{Area: "PageReference", API: "PageReference(partialURL)", Status: StatusSupported, Notes: "Builds a VM-local PageReference from a partial URL with mutable parameters and headers."},
	{Area: "PageReference", API: "PageReference(record)", Status: StatusSupported, Notes: "Builds a Visualforce PageReference from a local ApexPage SObject record."},
	{Area: "QuickAction", API: "QuickAction.describeAvailableActions", Status: StatusPartial, Notes: "Local QuickAction metadata and deterministic DTO results; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.describeAvailableQuickActions(String)", Status: StatusPartial, Notes: "Local QuickAction metadata and deterministic DTO results; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.describeQuickActions(List<String>)", Status: StatusPartial, Notes: "Local QuickAction metadata and deterministic DTO results; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.performQuickAction", Status: StatusPartial, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.performQuickAction(QuickAction.QuickActionRequest)", Status: StatusPartial, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.performQuickAction(QuickAction.QuickActionRequest,Boolean)", Status: StatusPartial, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.performQuickActions(List<QuickAction.QuickActionRequest>)", Status: StatusPartial, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.performQuickActions(List<QuickAction.QuickActionRequest>,Boolean)", Status: StatusPartial, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.retrieveQuickActionTemplate(String,Id)", Status: StatusPartial, Notes: "Local QuickAction metadata and deterministic DTO results; no live UI action service execution."},
	{Area: "QuickAction", API: "QuickAction.retrieveQuickActionTemplates(List<String>,Id)", Status: StatusPartial, Notes: "Local QuickAction metadata and deterministic DTO results; no live UI action service execution."},
	{Area: "Request", API: "Request.getCurrent()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "Request", API: "Request.getQuiddity()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "Request", API: "Request.getRequestId()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "Request", API: "RequestImpl.getCurrent()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "ResetPasswordResult", API: "ResetPasswordResult.getPassword()", Status: StatusUnsupported, Notes: "Password reset output is produced by Salesforce identity services and is not generated locally."},
	{Area: "Sandbox", API: "SandboxContext.organizationId()", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Sandbox", API: "SandboxContext.sandboxId()", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Sandbox", API: "SandboxContext.sandboxName()", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Sandbox", API: "SandboxPostCopy.runApexClass(SandboxContext)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Schedulable", API: "Schedulable.execute(SchedulableContext)", Status: StatusSupported, Notes: "Queues and drains local Scheduled Apex jobs during Test.stopTest with deterministic CronTrigger IDs."},
	{Area: "Schedulable", API: "SchedulableContext.getTriggerId()", Status: StatusSupported, Notes: "Queues and drains local Scheduled Apex jobs during Test.stopTest with deterministic CronTrigger IDs."},
	{Area: "Search", API: "Search.find(String,Object)", Status: StatusPartial, Notes: "Accepts recognized local AccessLevel or SuggestionOption object values against deterministic local org search; no external ranking, stemming, synonyms, or language model."},
	{Area: "Search", API: "Search.query(String,Object)", Status: StatusPartial, Notes: "Accepts recognized local AccessLevel or SuggestionOption object values against deterministic local org SOSL; no external ranking, stemming, synonyms, or language model."},
	{Area: "Search", API: "Search.suggest(String,String,Object)", Status: StatusPartial, Notes: "Accepts recognized SuggestionOption values and returns deterministic local org suggestions; no external suggestion service."},
	{Area: "Search", API: "Search.suggest(String,String,Object,Object)", Status: StatusPartial, Notes: "Accepts recognized SuggestionOption and AccessLevel values for deterministic local org suggestions; no external suggestion service."},
	{Area: "System", API: "System.enqueueJob(Object,Object)", Status: StatusPartial, Notes: "Accepts local AsyncOptions maximumQueueableStackDepth for queueable chaining and Test.stopTest drain behavior; delay semantics are not modeled."},
	{Area: "System", API: "System.runAs(Object,Object)", Status: StatusPartial, Notes: "Tracks local package-version test context without installing or licensing packages."},
	{Area: "System", API: "System.runAs(Package.Version)", Status: StatusPartial, Notes: "Tracks local package-version test context without installing or licensing packages."},
	{Area: "System", API: "System.schedule(String,String,Object)", Status: StatusSupported, Notes: "Queues and drains local Scheduled Apex jobs during Test.stopTest with deterministic CronTrigger IDs."},
	{Area: "Test", API: "Test.enableChangeDataCapture()", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Test", API: "Test.getEventBus()", Status: StatusPartial, Notes: "Returns a local event-bus test broker that delivers queued platform-event triggers; no live Salesforce event-bus service is contacted."},
	{Area: "Test", API: "Test.getExternalService()", Status: StatusPartial, Notes: "Returns a deterministic local external-service harness and fences live service execution."},
	{Area: "Test", API: "Test.invokeContinuationMethod(Object,Continuation)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Test", API: "Test.invokePage(PageReference)", Status: StatusSupported, Notes: "Returns a typed Component.apex.page handle in test context without rendering Visualforce."},
	{Area: "Test", API: "Test.newSendEmailQuickActionDefaults(Id,Id)", Status: StatusSupported, Notes: "Builds deterministic local send-email QuickAction defaults for test execution."},
	{Area: "Test", API: "Test.setContinuationResponse(String,HttpResponse)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Test", API: "Test.setCurrentPageReference(Object)", Status: StatusPartial, Notes: "Accepts local PageReference object values; arbitrary Object values remain rejected."},
	{Area: "Test", API: "Test.testInstall(InstallHandler,Version)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Test", API: "Test.testInstall(InstallHandler,Version,Boolean)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Test", API: "Test.testNotificationActionHandler(Messaging.NotificationActionHandler,Messaging.ActionableNotification)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Test", API: "Test.testSandboxPostCopyScript(SandboxPostCopy,Id,Id,String)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Test", API: "Test.testSandboxPostCopyScript(SandboxPostCopy,Id,Id,String,Boolean)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "Test", API: "Test.testUninstall(UninstallHandler)", Status: StatusSupported, Notes: "Invokes the local test harness implementation; no live Salesforce service is contacted."},
	{Area: "TrailblazerIdentity", API: "TrailblazerIdentity.generateUserEmailVerificationToken(String,String,String)", Status: StatusUnsupported, Notes: "Trailblazer identity service calls are not executed by the local Apex runtime."},
	{Area: "TrailblazerIdentity", API: "TrailblazerIdentity.getUserOrgInfo(List<String>)", Status: StatusUnsupported, Notes: "Trailblazer identity service calls are not executed by the local Apex runtime."},
	{Area: "TrailblazerIdentity", API: "TrailblazerIdentity.splunkLog(String,String)", Status: StatusUnsupported, Notes: "Trailblazer identity service calls are not executed by the local Apex runtime."},
	{Area: "UIRequest", API: "UIRequest.getCurrent()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "UIRequest", API: "UIRequest.getRequestHeader(String)", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "UserInfo", API: "UserInfo.hasPackageLicense(Id)", Status: StatusSupported, Notes: "Checks local PackageLicense and UserPackageLicense records for the current runAs/default user."},
	{Area: "UserInfo", API: "UserInfo.isCurrentUserLicensedForPackage(Id)", Status: StatusSupported, Notes: "Checks local PackageLicense and UserPackageLicense records for the current runAs/default user."},
	{Area: "WebServiceCallout", API: "WebServiceCallout.invoke(Object,Object,Map,List)", Status: StatusPartial, Notes: "Routes generated SOAP callouts through registered WebServiceMock implementations and materializes a deterministic local response shell when no mock is registered; real outbound SOAP transport is not executed."},
	{Area: "WebServiceCallout", API: "WebServiceCallout.invoke(Object,Object,Map<String,Object>,List<String>)", Status: StatusPartial, Notes: "Routes generated SOAP callouts through registered WebServiceMock implementations and materializes a deterministic local response shell when no mock is registered; real outbound SOAP transport is not executed."},
	{Area: "Pattern", API: "Matcher.find", Status: StatusPartial, Notes: "Go regexp-backed Java subset with local match state; Java-only matcher and regex features remain fenced."},
	{Area: "Pattern", API: "Matcher.group", Status: StatusPartial, Notes: "Returns local whole-match and capture groups after find/matches over the supported regex subset; Java-only matcher features remain fenced."},
	{Area: "Pattern", API: "Matcher.matches", Status: StatusPartial, Notes: "Whole-string matching over the local Go regexp-backed Java subset; Java-only regex features remain fenced."},
	{Area: "Pattern", API: "Pattern.compile", Status: StatusPartial, Notes: "Compiles the local Go regexp-backed Java subset with common flags and quote escapes; Java-only regex classes and flags remain fenced."},
	{Area: "Pattern", API: "Pattern.matches", Status: StatusPartial, Notes: "Whole-string matching over the local Go regexp-backed Java subset; Java-only regex features remain fenced."},
	{Area: "Schema", API: "Schema.describeSObjects(List<String>)", Status: StatusPartial, Notes: "Local metadata-backed object names, labels, key prefixes, access booleans, fields, record types, and SObjectType tokens; full org metadata parity is not modeled."},
	{Area: "Schema", API: "Schema.getGlobalDescribe()", Status: StatusPartial, Notes: "Local metadata-backed describe map for loaded standard and project objects; full org metadata parity is not modeled."},
	{Area: "Schema", API: "Schema.describeDataCategoryGroups(List<String>)", Status: StatusPartial, Notes: "Deterministic local data category group describes from org metadata; empty when no metadata is loaded."},
	{Area: "Schema", API: "Schema.describeDataCategoryGroupStructures(List<Schema.DataCategoryGroupSobjectTypePair>,Boolean)", Status: StatusPartial, Notes: "Deterministic local data category structures from org metadata; no external category service lookup."},
	{Area: "Schema", API: "DescribeFieldResult", Status: StatusPartial, Notes: "Local metadata-backed field labels, picklists, reference targets, and access/create/update booleans; full org metadata parity is not modeled."},
	{Area: "Schema", API: "DescribeSObjectResult", Status: StatusPartial, Notes: "Local metadata-backed object labels, key prefixes, query/search flags, fields, record types, and child relationships; full org metadata parity is not modeled."},
	{Area: "Search", API: "Search.query / SOSL FIND", Status: StatusPartial, Notes: "Parses RETURNING clauses and returns deterministic rows from fixed search results or local org records; no ranking, stemming, synonyms, language, or external search service."},
	{Area: "Search", API: "Search.query(String,AccessLevel)", Status: StatusPartial, Notes: "Uses deterministic local org SOSL with AccessLevel permission checks; no ranking, stemming, synonyms, language, or external search service."},
	{Area: "Search", API: "Search.find", Status: StatusPartial, Notes: "Returns deterministic SearchResult DTOs from fixed search results or local org records; no external ranking, stemming, synonyms, language, or rich snippets."},
	{Area: "Search", API: "Search.find(String,AccessLevel)", Status: StatusPartial, Notes: "Uses deterministic local org search with AccessLevel permission checks; no external ranking, stemming, synonyms, language, or rich snippets."},
	{Area: "Search", API: "Search.suggest", Status: StatusPartial, Notes: "Returns deterministic local org suggestion DTOs from name-like fields; no external suggestion service."},
	{Area: "Search", API: "Search.suggest(String,String,Search.SuggestionOption)", Status: StatusPartial, Notes: "Returns deterministic local org suggestions and respects local limit options; no external suggestion service."},
	{Area: "Search", API: "Search.suggest(String,String,Search.SuggestionOption,AccessLevel)", Status: StatusPartial, Notes: "Returns deterministic local org suggestions with AccessLevel permission checks; no external suggestion service."},
	{Area: "SObject", API: "SObject.setOptions(Database.DMLOptions)", Status: StatusSupported, Notes: "Stores a cloned DMLOptions value on the local SObject for later DML option use."},
	{Area: "String", API: "String.contains", Status: StatusSupported, Notes: "UTF-8 string contains."},
	{Area: "String", API: "String.endsWith", Status: StatusSupported, Notes: "UTF-8 string suffix."},
	{Area: "String", API: "String.equalsIgnoreCase", Status: StatusSupported, Notes: "Unicode simple fold."},
	{Area: "String", API: "String.indexOf", Status: StatusSupported, Notes: "UTF-8 byte index behavior from Go strings."},
	{Area: "String", API: "String.isBlank", Status: StatusSupported, Notes: "Null and whitespace."},
	{Area: "String", API: "String.isNotBlank", Status: StatusSupported, Notes: "Null and whitespace."},
	{Area: "String", API: "String.join", Status: StatusSupported, Notes: "List values and separator."},
	{Area: "String", API: "String.lastIndexOf", Status: StatusSupported, Notes: "UTF-8 byte index behavior from Go strings."},
	{Area: "String", API: "String.length", Status: StatusSupported, Notes: "Counts runes."},
	{Area: "String", API: "String.replace", Status: StatusSupported, Notes: "Literal replacement."},
	{Area: "String", API: "String.split", Status: StatusPartial, Notes: "Uses local Java-regex-like split for the supported Go regexp subset, including limits and \\Q...\\E quote escapes; empty-match regexes and Java-only features remain fenced."},
	{Area: "String", API: "String.startsWith", Status: StatusSupported, Notes: "UTF-8 string prefix."},
	{Area: "String", API: "String.substring", Status: StatusSupported, Notes: "Rune-indexed substring."},
	{Area: "String", API: "String.toLowerCase", Status: StatusSupported, Notes: "Go Unicode lowercasing."},
	{Area: "String", API: "String.toUpperCase", Status: StatusSupported, Notes: "Go Unicode uppercasing."},
	{Area: "String", API: "String.trim", Status: StatusSupported, Notes: "Unicode whitespace trim."},
	{Area: "String", API: "String.valueOf", Status: StatusSupported, Notes: "Local value string conversion."},
	{Area: "System", API: "System.assert", Status: StatusSupported, Notes: "Assertion failure returns runtime error."},
	{Area: "System", API: "System.assertEquals", Status: StatusSupported, Notes: "Assertion failure returns runtime error."},
	{Area: "System", API: "System.debug", Status: StatusSupported, Notes: "Collected in result debug output."},
	{Area: "Test", API: "Test.getStandardPricebookId", Status: StatusPartial, Notes: "Deterministic test-context-only ID."},
	{Area: "Test", API: "Test.createStubQueryRow", Status: StatusPartial, Notes: "Builds local SObject rows from field maps for SOQL stub providers."},
	{Area: "Test", API: "Test.createStubQueryRow(Schema.SObjectType,Map<String,Object>)", Status: StatusSupported, Notes: "Builds one local SObject row from a field map for SOQL stub providers."},
	{Area: "Test", API: "Test.createStubQueryRows", Status: StatusPartial, Notes: "Builds local SObject row lists from field maps for SOQL stub providers."},
	{Area: "Test", API: "Test.createStubQueryRows(Schema.SObjectType,List<Map<String,Object>>)", Status: StatusSupported, Notes: "Builds local SObject row lists from field maps for SOQL stub providers."},
	{Area: "Test", API: "Test.createSoqlStub(Schema.SObjectType,SoqlStubProvider)", Status: StatusSupported, Notes: "Registers test-local SOQL stubs per SObject type."},
	{Area: "Test", API: "Test.createStub(Type,StubProvider)", Status: StatusSupported, Notes: "Creates dynamic test stubs backed by StubProvider."},
	{Area: "Test", API: "Test.isRunningTest", Status: StatusSupported, Notes: "Reflects local test context."},
	{Area: "Test", API: "Test.loadData", Status: StatusPartial, Notes: "Loads CSV static-resource content with Go CSV parsing, typed field coercion, DML routing, missing-resource errors, and bad-header diagnostics; full Salesforce fixture semantics are not modeled."},
	{Area: "Test", API: "Test.setCurrentPage(PageReference)", Status: StatusSupported, Notes: "Sets the VM-local current PageReference in test context."},
	{Area: "Test", API: "Test.setCurrentPageReference(PageReference)", Status: StatusSupported, Notes: "Sets the VM-local current PageReference in test context."},
	{Area: "Test", API: "Test.setMock", Status: StatusPartial, Notes: "HttpCalloutMock and WebServiceMock routing for local tests; live transport is not executed."},
	{Area: "Test", API: "Test.startTest", Status: StatusPartial, Notes: "Resets the active governor window for supported local counters; unmodeled service counters remain local boundaries."},
	{Area: "Test", API: "Test.stopTest", Status: StatusPartial, Notes: "Restores outer governor counters and drains supported async work; unmodeled async/service work remains outside the local model."},
	{Area: "Time", API: "Time.hour", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.minute", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.newInstance", Status: StatusSupported, Notes: "Validates time parts."},
	{Area: "Time", API: "Time.second", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.valueOf", Status: StatusSupported, Notes: "Parses supported time strings."},
	{Area: "TimeZone", API: "TimeZone.getDisplayName", Status: StatusSupported, Notes: "Returns deterministic display names for local timezone values."},
	{Area: "TimeZone", API: "TimeZone.getID", Status: StatusSupported, Notes: "Returns local timezone IDs."},
	{Area: "TimeZone", API: "TimeZone.getOffset", Status: StatusSupported, Notes: "Returns offsets from the deterministic local timezone model."},
	{Area: "TimeZone", API: "TimeZone.getTimeZone", Status: StatusSupported, Notes: "Resolves timezone IDs into local timezone values."},
	{Area: "Type", API: "Type.forName", Status: StatusPartial, Notes: "Local class/type token lookup."},
	{Area: "Type", API: "Type.getName", Status: StatusSupported, Notes: "Returns local type token name."},
	{Area: "Type", API: "Type.newInstance", Status: StatusSupported, Notes: "Constructs local classes through zero-argument constructor dispatch and rejects uninstantiable built-ins."},
	{Area: "URL", API: "URL.getOrgDomainUrl", Status: StatusSupported, Notes: "Deterministic local org URL."},
	{Area: "URL", API: "URL.getSalesforceBaseUrl", Status: StatusSupported, Notes: "Deterministic local base URL."},
	{Area: "Unsupported", API: "unimplemented platform/stdlib calls", Status: StatusSupported, Notes: "Typed UnsupportedFeature errors with stable message text."},
	{Area: "UserInfo", API: "UserInfo.getLanguage", Status: StatusSupported, Notes: "Returns the current runAs/default user's local language value."},
	{Area: "UserInfo", API: "UserInfo.getLocale", Status: StatusSupported, Notes: "Returns the current runAs/default user's local locale value."},
	{Area: "UserInfo", API: "UserInfo.getFirstName", Status: StatusSupported, Notes: "Returns the current runAs/default user's local first name."},
	{Area: "UserInfo", API: "UserInfo.getLastName", Status: StatusSupported, Notes: "Returns the current runAs/default user's local last name."},
	{Area: "UserInfo", API: "UserInfo.getName", Status: StatusSupported, Notes: "Returns the current runAs/default user's local display name."},
	{Area: "UserInfo", API: "UserInfo.getOrganizationId", Status: StatusSupported, Notes: "Returns the deterministic local org identity."},
	{Area: "UserInfo", API: "UserInfo.getProfileId", Status: StatusSupported, Notes: "Returns the current runAs/default user's local profile id."},
	{Area: "UserInfo", API: "UserInfo.getSessionId", Status: StatusSupported, Notes: "Returns the deterministic empty local session value."},
	{Area: "UserInfo", API: "UserInfo.getTimeZone", Status: StatusSupported, Notes: "Returns the deterministic local user timezone."},
	{Area: "UserInfo", API: "UserInfo.getUserEmail", Status: StatusSupported, Notes: "Returns the current runAs/default user's local email value."},
	{Area: "UserInfo", API: "UserInfo.getUserId", Status: StatusSupported, Notes: "Returns the current runAs/default user's local user id."},
	{Area: "UserInfo", API: "UserInfo.getUserName", Status: StatusSupported, Notes: "Returns the current runAs/default user's local username."},
	{Area: "UserInfo", API: "UserInfo.getUserType", Status: StatusSupported, Notes: "Returns the current runAs/default user's local user type."},
	{Area: "UserInfo", API: "UserInfo.isMultiCurrencyOrganization", Status: StatusSupported, Notes: "Returns the local org multi-currency metadata flag."},
}
