package capability

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
)

type StdlibEntry struct {
	Area   string `json:"area"`
	API    string `json:"api"`
	Status Status `json:"status"`
	Notes  string `json:"notes,omitempty"`
}

func StdlibMatrix() []StdlibEntry {
	entries := append([]StdlibEntry(nil), stdlibEntries...)
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Area == entries[j].Area {
			return entries[i].API < entries[j].API
		}
		return entries[i].Area < entries[j].Area
	})
	return entries
}

func WriteStdlibJSON(w io.Writer) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(StdlibMatrix())
}

func WriteStdlibMarkdown(w io.Writer) error {
	if _, err := fmt.Fprintln(w, "# Standard Library Coverage"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\nGenerated from the first-party compat plugin capability catalog."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\nStatus values match the compatibility dashboard: `supported`, `partial`, `stub`, `unsupported`, and `unknown`."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\n| Area | API | Status | Notes |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| --- | --- | --- | --- |"); err != nil {
		return err
	}
	for _, entry := range StdlibMatrix() {
		if _, err := fmt.Fprintf(w, "| %s | `%s` | `%s` | %s |\n", entry.Area, entry.API, entry.Status, entry.Notes); err != nil {
			return err
		}
	}
	return nil
}

var stdlibEntries = []StdlibEntry{
	{Area: "AccessLevel", API: "AccessLevel.withPermissionSetId(String)", Status: StatusSupported, Notes: "Creates a local permission-set-scoped user-mode token used by supported SOQL and DML permission checks."},
	{Area: "Answers", API: "Answers.findSimilar(Question)", Status: StatusSupported, Notes: "Local execution returns a deterministic empty List<Id> without performing hosted similarity search."},
	{Area: "ApexPages", API: "ApexPages.addMessage", Status: StatusSupported, Notes: "Stores page messages on the VM instance."},
	{Area: "ApexPages", API: "ApexPages.addMessage(ApexPages.Message)", Status: StatusSupported, Notes: "Stores page messages on the VM instance."},
	{Area: "ApexPages", API: "ApexPages.addMessages(Exception)", Status: StatusSupported, Notes: "Converts supported exception values into VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.addMessages(Object)", Status: StatusSupported, Notes: "Converts supported exception and message values into VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.currentPage", Status: StatusSupported, Notes: "Returns a deterministic local PageReference."},
	{Area: "ApexPages", API: "ApexPages.currentPage()", Status: StatusSupported, Notes: "Returns the VM-local PageReference."},
	{Area: "ApexPages", API: "ApexPages.getMessages", Status: StatusSupported, Notes: "Returns VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.getMessages()", Status: StatusSupported, Notes: "Returns VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.hasMessages", Status: StatusSupported, Notes: "Checks VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.hasMessages()", Status: StatusSupported, Notes: "Checks VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.hasMessages(ApexPages.Severity)", Status: StatusSupported, Notes: "Checks VM-local page messages by severity."},
	{Area: "ApexPages", API: "ApexPages.Message", Status: StatusSupported, Notes: "Constructor, getters, add/get/has message state, and Visualforce action reset behavior are modeled."},
	{Area: "ApexPages", API: "Visualforce full rendering lifecycle", Status: StatusUnsupported, Notes: "Full Visualforce rendering lifecycle requires the hosted renderer and is fenced by PageReference rendering diagnostics locally."},
	{Area: "Boolean", API: "Boolean.valueOf(Object)", Status: StatusSupported, Notes: "Converts supported local field/object values into Boolean values."},
	{Area: "Boolean", API: "Boolean.valueOf(String)", Status: StatusSupported, Notes: "Converts strings to Boolean using Apex-shaped true/false parsing."},
	{Area: "Assert", API: "Assert.areEqual", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.areNotEqual", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.fail", Status: StatusSupported, Notes: "Raises local System.AssertException with optional message text."},
	{Area: "Assert", API: "Assert.isFalse", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.isNotNull", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.isNull", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Assert", API: "Assert.isTrue", Status: StatusSupported, Notes: "Routes through local assertion failures with optional message text."},
	{Area: "Approval", API: "Approval.process(Approval.ProcessRequest)", Status: StatusSupported, Notes: "Runs a seeded local ProcessDefinition, ProcessNode, ProcessInstance, and ProcessInstanceWorkitem engine for submit, approve, and reject request shapes."},
	{Area: "Approval", API: "Approval.process(Approval.ProcessRequest, Boolean)", Status: StatusSupported, Notes: "Runs the seeded local approval engine with allOrNone error shaping for submit, approve, and reject request shapes."},
	{Area: "Approval", API: "Approval.process(List<Approval.ProcessRequest>)", Status: StatusSupported, Notes: "Runs ordered local submit and workitem request lists and rolls back earlier successful local approval records when the default allOrNone path fails later in the list."},
	{Area: "Approval", API: "Approval.process(List<Approval.ProcessRequest>, Boolean)", Status: StatusSupported, Notes: "Runs ordered local submit and workitem request lists, returning per-request errors when allOrNone is false and rolling back the local list transaction when allOrNone is true."},
	{Area: "Approval", API: "Approval.process hosted approval engine routing", Status: StatusUnsupported, Notes: "Hosted criteria evaluation, queue/group approver routing, and live approval service routing require Salesforce approval services."},
	{Area: "BusinessHours", API: "BusinessHours.add(Id, Datetime, Long)", Status: StatusSupported, Notes: "Runs deterministic local week-schedule math from seeded BusinessHours, Holiday, OperatingHours, and OperatingHoursHoliday records with timezone handling, all-day closures, partial-day closures, recurring holidays, and linked holidays."},
	{Area: "BusinessHours", API: "BusinessHours.addGmt(Id, Datetime, Long)", Status: StatusSupported, Notes: "Runs deterministic local calendar math from seeded BusinessHours, Holiday, OperatingHours, and OperatingHoursHoliday records with GMT Datetime output."},
	{Area: "BusinessHours", API: "BusinessHours.diff(String, Datetime, Datetime)", Status: StatusSupported, Notes: "Counts deterministic local business milliseconds across seeded week schedules, timezones, all-day closures, partial-day closures, recurring holidays, and linked holidays."},
	{Area: "BusinessHours", API: "BusinessHours.isWithin(String, Datetime)", Status: StatusSupported, Notes: "Checks seeded local week schedules, timezones, Holiday closures, OperatingHoursHoliday links, partial-day closures, and recurring holidays."},
	{Area: "BusinessHours", API: "BusinessHours.nextStartDate(Id, Datetime)", Status: StatusSupported, Notes: "Finds the next deterministic local start from seeded week schedules, timezones, Holiday closures, OperatingHoursHoliday links, partial-day closures, and recurring holidays."},
	{Area: "BusinessHours", API: "BusinessHours malformed local holiday metadata", Status: StatusUnsupported, Notes: "Malformed seeded holiday metadata raises a stable UnsupportedFeature diagnostic naming the unsupported local field shape."},
	{Area: "Crypto", API: "Crypto.generateDigest", Status: StatusSupported, Notes: "MD5, SHA-1/SHA1, SHA-256/SHA256, SHA-384/SHA384, SHA-512/SHA512, and SHA3-256/384/512 digests are fixture-pinned, with Salesforce-shaped SecurityException diagnostics for unknown names."},
	{Area: "Database", API: "Database.countQuery", Status: StatusSupported, Notes: "Dynamic SOQL count execution against the local org with local AccessLevel parsing."},
	{Area: "Database", API: "Database.convertLead", Status: StatusSupported, Notes: "Local lead conversion creates Account, Contact, and optional Opportunity records and updates Lead conversion fields."},
	{Area: "Database", API: "Database.delete", Status: StatusSupported, Notes: "DML pipeline with result/error shapes and local AccessLevel parsing for supported SObjects."},
	{Area: "Database", API: "Database.deleteAsync", Status: StatusSupported, Notes: "Local async delete alias runs through the DML pipeline and returns DeleteResult shape."},
	{Area: "Database", API: "Database.deleteImmediate", Status: StatusSupported, Notes: "Local immediate delete alias runs through the DML pipeline and returns DeleteResult shape."},
	{Area: "Database", API: "Database.countQueryWithBinds", Status: StatusSupported, Notes: "Bind-map dynamic SOQL count execution with local AccessLevel parsing."},
	{Area: "Database", API: "Database.emptyRecycleBin", Status: StatusSupported, Notes: "Local hard-delete result shape with allOrNone rollback for supported SObjects."},
	{Area: "Database", API: "Database.executeBatch", Status: StatusSupported, Notes: "Queues local Batchable jobs and drains start/execute chunks/finish during Test.stopTest."},
	{Area: "Database", API: "Database.getAsyncLocator", Status: StatusSupported, Notes: "Returns deterministic VM-local locator strings for local result and locator objects."},
	{Area: "Database", API: "Database.getAsyncDeleteResult", Status: StatusSupported, Notes: "Returns materialized local DeleteResult values and rejects unknown async locator strings instead of fabricating pending results."},
	{Area: "Database", API: "Database.getAsyncSaveResult", Status: StatusSupported, Notes: "Returns materialized local SaveResult values and rejects unknown async locator strings instead of fabricating pending results."},
	{Area: "Database", API: "Database.getCursor", Status: StatusSupported, Notes: "Local cursor over supported SOQL results with deterministic fetch windows."},
	{Area: "Database", API: "Database.getCursorWithBinds", Status: StatusSupported, Notes: "Bind-map local cursor over supported SOQL results with deterministic fetch windows."},
	{Area: "Database", API: "Database.getDeleted", Status: StatusSupported, Notes: "Returns local soft-deleted record tombstones whose deletion timestamp falls within the requested sync window."},
	{Area: "Database", API: "Database.getQueryLocator", Status: StatusSupported, Notes: "Supported SOQL executes eagerly for local batch scopes with local AccessLevel parsing."},
	{Area: "Database", API: "Database.getQueryLocatorWithBinds", Status: StatusSupported, Notes: "Bind-map dynamic SOQL locator execution with iterable local query locators."},
	{Area: "Database", API: "Database.getPaginationCursor", Status: StatusSupported, Notes: "Local pagination cursor over supported SOQL results with deterministic fetch windows."},
	{Area: "Database", API: "Database.getPaginationCursorWithBinds", Status: StatusSupported, Notes: "Bind-map local pagination cursor over supported SOQL results with deterministic fetch windows."},
	{Area: "Database", API: "Database.getUpdated", Status: StatusSupported, Notes: "Returns local record IDs whose system-modified timestamp falls within the requested sync window."},
	{Area: "Database", API: "Database.insert", Status: StatusSupported, Notes: "DML pipeline with result/error shapes and local AccessLevel parsing for supported SObjects."},
	{Area: "Database", API: "Database.insertAsync", Status: StatusSupported, Notes: "Local async insert alias runs through the DML pipeline and returns SaveResult shape."},
	{Area: "Database", API: "Database.insertImmediate", Status: StatusSupported, Notes: "Local immediate insert alias runs through the DML pipeline and returns SaveResult shape."},
	{Area: "Database", API: "Database.lock", Status: StatusSupported, Notes: "Local row-lock result shape with allOrNone rollback for supported SObjects."},
	{Area: "Database", API: "Database.merge", Status: StatusSupported, Notes: "Local merge behavior with result shape and AccessLevel parsing for supported schema-backed data."},
	{Area: "Database", API: "Database.query", Status: StatusSupported, Notes: "Dynamic SOQL execution against the local org with catchable QueryException parse errors."},
	{Area: "Database", API: "Database.queryWithBinds", Status: StatusSupported, Notes: "Bind-map dynamic SOQL execution with scalar and collection binds."},
	{Area: "Database", API: "Database.releaseSavepoint", Status: StatusSupported, Notes: "Releases the selected local savepoint and later savepoints without rolling back org state."},
	{Area: "Database", API: "Database.rollback", Status: StatusSupported, Notes: "Restores the local org-state snapshot for the selected savepoint."},
	{Area: "Database", API: "Database.setSavepoint", Status: StatusSupported, Notes: "Local org-state snapshots with later-savepoint invalidation."},
	{Area: "Database", API: "Database.treeSave", Status: StatusSupported, Notes: "Local parent insert/update plus first-level child insert/update with NestedSaveResult relationship result shape."},
	{Area: "Database", API: "Database.UnitOfWork", Status: StatusSupported, Notes: "Queues local DML operations and applies them on commitWork; discardWork drops pending local work."},
	{Area: "Database", API: "Database.undelete", Status: StatusSupported, Notes: "Soft-delete restoration with local AccessLevel parsing for supported local records."},
	{Area: "Database", API: "Database.unlock", Status: StatusSupported, Notes: "Local row-unlock result shape with allOrNone rollback for supported SObjects."},
	{Area: "Database", API: "Database.update", Status: StatusSupported, Notes: "DML pipeline with result/error shapes and local AccessLevel parsing for supported SObjects."},
	{Area: "Database", API: "Database.updateAsync", Status: StatusSupported, Notes: "Local async update alias runs through the DML pipeline and returns SaveResult shape."},
	{Area: "Database", API: "Database.updateImmediate", Status: StatusSupported, Notes: "Local immediate update alias runs through the DML pipeline and returns SaveResult shape."},
	{Area: "Database", API: "Database.upsert", Status: StatusSupported, Notes: "Schema-backed external-ID matching with local AccessLevel parsing for supported local records."},
	{Area: "Date", API: "Date.addMonths", Status: StatusSupported, Notes: "Local Gregorian month arithmetic with end-of-month clamping."},
	{Area: "Date", API: "Date.addYears", Status: StatusSupported, Notes: "Local Gregorian year arithmetic with leap-day clamping."},
	{Area: "Date", API: "Date.addDays", Status: StatusSupported, Notes: "Local Gregorian day arithmetic."},
	{Area: "Date", API: "Date.newInstance", Status: StatusSupported, Notes: "Validates date parts."},
	{Area: "Date", API: "Date.today", Status: StatusSupported, Notes: "Returns the deterministic local runtime date."},
	{Area: "Date", API: "Date.valueOf", Status: StatusSupported, Notes: "Parses supported date strings."},
	{Area: "Datetime", API: "Datetime.addDays", Status: StatusSupported, Notes: "UTC-local day arithmetic."},
	{Area: "Datetime", API: "Datetime.addHours", Status: StatusSupported, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addMinutes", Status: StatusSupported, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addMonths", Status: StatusSupported, Notes: "UTC-local month arithmetic with end-of-month clamping."},
	{Area: "Datetime", API: "Datetime.addSeconds", Status: StatusSupported, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addYears", Status: StatusSupported, Notes: "UTC-local year arithmetic with leap-day clamping."},
	{Area: "Datetime", API: "Datetime.format", Status: StatusSupported, Notes: "Formats using the deterministic local timezone model."},
	{Area: "Datetime", API: "Datetime.formatGmt", Status: StatusSupported, Notes: "Formats using GMT."},
	{Area: "Datetime", API: "Datetime.newInstance", Status: StatusSupported, Notes: "Validates date and time parts."},
	{Area: "Datetime", API: "Datetime.now", Status: StatusSupported, Notes: "Returns the deterministic local runtime datetime."},
	{Area: "Datetime", API: "Datetime.valueOf", Status: StatusSupported, Notes: "Parses supported datetime strings."},
	{Area: "Decimal", API: "Decimal.divide(Decimal,Integer,RoundingMode)", Status: StatusSupported, Notes: "Divides local Decimal values with explicit scale and RoundingMode."},
	{Area: "Decimal", API: "Decimal.doubleValue", Status: StatusSupported, Notes: "Returns local Decimal value."},
	{Area: "Decimal", API: "Decimal.intValue", Status: StatusSupported, Notes: "Truncates to integer."},
	{Area: "Decimal", API: "Decimal.round", Status: StatusSupported, Notes: "Oracle-pinned finite Decimal rounding uses Salesforce default HALF_EVEN ties and explicit RoundingMode behavior."},
	{Area: "Decimal", API: "Decimal.setScale", Status: StatusSupported, Notes: "Oracle-pinned finite Decimal scaling covers positive and negative scales, RoundingMode ties, UNNECESSARY MathException, and Salesforce scale bounds."},
	{Area: "EncodingUtil", API: "EncodingUtil.base64Decode", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.base64Encode", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.convertFromHex", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.convertToHex", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.urlDecode", Status: StatusSupported, Notes: "Oracle-pinned URL form decoding covers UTF-8, US-ASCII replacement, ISO-8859-1 aliases, and UTF-16 mixed escaped/plain input."},
	{Area: "EncodingUtil", API: "EncodingUtil.urlEncode", Status: StatusSupported, Notes: "Oracle-pinned URL form encoding covers UTF-8, US-ASCII replacement, ISO-8859-1 aliases, and UTF-16 escaped output."},
	{Area: "Exception", API: "InvalidParameterValueException constructors", Status: StatusSupported, Notes: "Supports zero-arg, message, cause, and existing platform-specific constructor shapes."},
	{Area: "Exception", API: "NoAccessException constructors", Status: StatusSupported, Notes: "Supports zero-arg, message, cause, and message-plus-cause constructor shapes."},
	{Area: "Exception", API: "NoDataFoundException constructors", Status: StatusSupported, Notes: "Supports zero-arg, message, cause, and message-plus-cause constructor shapes."},
	{Area: "Exception", API: "NullPointerException constructors", Status: StatusSupported, Notes: "Supports zero-arg, message, cause, and message-plus-cause constructor shapes."},
	{Area: "FeatureManagement", API: "FeatureManagement.checkPermission", Status: StatusSupported, Notes: "Checks local runAs user permissions, permission sets, and custom-permission assignments."},
	{Area: "HTTP", API: "Http.send(HttpRequest)", Status: StatusSupported, Notes: "Routes local callouts through registered HttpCalloutMock implementations and records local callout limits."},
	{Area: "HTTP", API: "HttpRequest", Status: StatusSupported, Notes: "Endpoint, method, headers, timeout, body, blob body, and local DTO accessors are modeled."},
	{Area: "HTTP", API: "HttpRequest client certificate local mock metadata", Status: StatusSupported, Notes: "Client certificate name and PEM accessors read deterministic local certificate metadata for mock-backed callouts."},
	{Area: "HTTP", API: "HttpRequest client certificate real TLS handshake", Status: StatusUnsupported, Notes: "Real mutual-TLS handshakes and Salesforce certificate-store delivery require hosted callout infrastructure."},
	{Area: "HTTP", API: "HttpResponse", Status: StatusSupported, Notes: "Status, status code, headers, body, blob body, and local DTO accessors are modeled."},
	{Area: "JSON", API: "JSON.deserialize", Status: StatusSupported, Notes: "Oracle-pinned DTO, SObject, primitive, collection, Object, string-key, and scalar-key map paths preserve duplicate-key last-value behavior and field order."},
	{Area: "JSON", API: "JSON.deserializeStrict", Status: StatusSupported, Notes: "Oracle-pinned strict DTO and SObject paths accept known fields, reject unknown fields with Salesforce-shaped diagnostics, and keep the last duplicate SObject field value."},
	{Area: "JSON", API: "JSON.deserializeUntyped", Status: StatusSupported, Notes: "Oracle-pinned untyped primitive, list, and map containers preserve order, collapse duplicate keys to the last value, and throw Salesforce-shaped oversized integer errors."},
	{Area: "JSON", API: "JSON.serialize", Status: StatusSupported, Notes: "Oracle-pinned serialization covers DTO, SObject, collection, map, primitive, enum, Object, and suppressApexObjectNulls paths with deterministic field order."},
	{Area: "JSON", API: "JSON.serializePretty", Status: StatusSupported, Notes: "Oracle-pinned pretty serialization covers DTO, SObject, collection, map, primitive, and Object paths with Salesforce-style spacing."},
	{Area: "Label", API: "Label.get(String,String)", Status: StatusSupported, Notes: "Resolves local custom label metadata with existing platform and managed-namespace fallbacks."},
	{Area: "Label", API: "Label.get(String,String,String)", Status: StatusSupported, Notes: "Resolves local custom label metadata for an explicit language, then falls back to the local label resolver."},
	{Area: "Label", API: "Label.translationExists(String,String,String)", Status: StatusSupported, Notes: "Returns true when local label metadata has a matching explicit language translation."},
	{Area: "Limits", API: "Limits.get*", Status: StatusSupported, Notes: "Returns deterministic local counters and configurable caps for all tracked getter families, including zero-valued local service counters."},
	{Area: "Limits", API: "Exact Salesforce governor accounting profiles", Status: StatusUnsupported, Notes: "Exact hosted governor deltas require Salesforce runtime accounting and remain outside local execution."},
	{Area: "Limits", API: "Limits.getAsyncCalls", Status: StatusSupported, Notes: "Returns the local async-call counter."},
	{Area: "Limits", API: "Limits.getLimitAsyncCalls", Status: StatusSupported, Notes: "Returns the local async-call limit."},
	{Area: "Math", API: "Math.abs", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.ceil", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.floor", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.max", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.min", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.pow", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.round", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.sqrt", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Messaging", API: "Messaging.SingleEmailMessage", Status: StatusSupported, Notes: "Common DTO setters/getters, recipient fields, template fields, body fields, flags, and local file attachment values are modeled."},
	{Area: "Messaging", API: "Messaging.sendEmail", Status: StatusSupported, Notes: "Returns ordered local SendEmailResult values, validates supported DTOs, captures sent messages with SendEmailOptions metadata, and increments local email limits."},
	{Area: "Messaging", API: "Messaging.sendEmail delivery transport", Status: StatusUnsupported, Notes: "Outbound delivery depends on Salesforce email services and remains fenced behind stable UnsupportedFeature diagnostics locally."},
	{Area: "Messaging", API: "Messaging.sendEmail(Messaging.Email[],Boolean)", Status: StatusSupported, Notes: "Returns ordered local SendEmailResult values for supported email message DTOs; outbound delivery remains hosted."},
	{Area: "Messaging", API: "Messaging.renderStoredEmailTemplate(String,String,String,Messaging.AttachmentRetrievalOption)", Status: StatusSupported, Notes: "Renders local stored EmailTemplate subject, HTML, text bodies, merge fields, static-resource attachments, Attachment rows, and ContentDocumentLink attachments for NONE, METADATA_ONLY, BODY, and METADATA_WITH_BODY."},
	{Area: "Messaging", API: "Messaging.renderStoredEmailTemplate(String,String,String,Messaging.AttachmentRetrievalOption,Boolean)", Status: StatusSupported, Notes: "Renders local stored templates like the four-argument overload and accepts updateEmailTemplateUsage without remote usage mutation."},
	{Area: "Messaging", API: "Messaging.renderStoredEmailTemplate hosted usage mutation", Status: StatusUnsupported, Notes: "Hosted EmailTemplate usage counters and send-side usage mutation require Salesforce email services."},
	{Area: "PageReference", API: "PageReference", Status: StatusSupported, Notes: "Constructor, URL, redirect, mutable parameters, headers, cookies, and current-page state are modeled."},
	{Area: "PageReference", API: "PageReference.getContent and getContentAsPDF", Status: StatusUnsupported, Notes: "Visualforce rendering and PDF generation require the hosted rendering service and raise stable UnsupportedFeature diagnostics locally."},
	{Area: "PageReference", API: "PageReference(partialURL)", Status: StatusSupported, Notes: "Builds a VM-local PageReference from a partial URL with mutable parameters and headers."},
	{Area: "PageReference", API: "PageReference(record)", Status: StatusSupported, Notes: "Builds a Visualforce PageReference from a local ApexPage SObject record."},
	{Area: "QuickAction", API: "QuickAction.describeAvailableActions", Status: StatusSupported, Notes: "Local QuickAction metadata, predefined default values, and deterministic DTO results are modeled."},
	{Area: "QuickAction", API: "QuickAction.describeAvailableQuickActions(String)", Status: StatusSupported, Notes: "Local QuickAction metadata, predefined default values, and deterministic DTO results are modeled."},
	{Area: "QuickAction", API: "QuickAction.describeQuickActions(List<String>)", Status: StatusSupported, Notes: "Local QuickAction metadata, predefined default values, and deterministic DTO results are modeled."},
	{Area: "QuickAction", API: "QuickAction.performQuickAction", Status: StatusSupported, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes."},
	{Area: "QuickAction", API: "QuickAction.performQuickAction(QuickAction.QuickActionRequest)", Status: StatusSupported, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes."},
	{Area: "QuickAction", API: "QuickAction.performQuickAction(QuickAction.QuickActionRequest,Boolean)", Status: StatusSupported, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes."},
	{Area: "QuickAction", API: "QuickAction.performQuickActions(List<QuickAction.QuickActionRequest>)", Status: StatusSupported, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes."},
	{Area: "QuickAction", API: "QuickAction.performQuickActions(List<QuickAction.QuickActionRequest>,Boolean)", Status: StatusSupported, Notes: "Returns deterministic local QuickActionResult DTOs for supported request shapes."},
	{Area: "QuickAction", API: "QuickAction.retrieveQuickActionTemplate(String,Id)", Status: StatusSupported, Notes: "Local QuickAction metadata, predefined default values, and deterministic template DTOs are modeled."},
	{Area: "QuickAction", API: "QuickAction.retrieveQuickActionTemplates(List<String>,Id)", Status: StatusSupported, Notes: "Local QuickAction metadata, predefined default values, and deterministic template DTOs are modeled."},
	{Area: "Request", API: "Request.getCurrent()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "Request", API: "Request.getQuiddity()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "Request", API: "Request.getRequestId()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "Request", API: "RequestImpl.getCurrent()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "ResetPasswordResult", API: "ResetPasswordResult.getPassword()", Status: StatusUnsupported, Notes: "Password reset output is produced by Salesforce identity services and is not generated locally."},
	{Area: "Sandbox", API: "SandboxContext.organizationId()", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Sandbox", API: "SandboxContext.sandboxId()", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Sandbox", API: "SandboxContext.sandboxName()", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Sandbox", API: "SandboxPostCopy.runApexClass(SandboxContext)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Schedulable", API: "Schedulable.execute(SchedulableContext)", Status: StatusSupported, Notes: "Queues and drains local Scheduled Apex jobs during Test.stopTest with deterministic CronTrigger IDs."},
	{Area: "Schedulable", API: "SchedulableContext.getTriggerId()", Status: StatusSupported, Notes: "Queues and drains local Scheduled Apex jobs during Test.stopTest with deterministic CronTrigger IDs."},
	{Area: "Search", API: "Search.find(String,Object)", Status: StatusSupported, Notes: "Accepts Object-cast AccessLevel values against deterministic local org search."},
	{Area: "Search", API: "Search.query(String,Object)", Status: StatusSupported, Notes: "Accepts Object-cast AccessLevel values against deterministic local org SOSL."},
	{Area: "Search", API: "Search.suggest(String,String,Object)", Status: StatusSupported, Notes: "Accepts Object-cast SuggestionOption values and returns deterministic local org suggestions."},
	{Area: "Search", API: "Search.suggest(String,String,Object,Object)", Status: StatusSupported, Notes: "Accepts Object-cast SuggestionOption and AccessLevel values for deterministic local org suggestions."},
	{Area: "Search", API: "Hosted search ranking and analyzers", Status: StatusUnsupported, Notes: "Ranking, stemming, synonyms, language analyzers, external indexes, and hosted suggestion services require Salesforce search infrastructure."},
	{Area: "System", API: "System.enqueueJob(Object,Object)", Status: StatusSupported, Notes: "Accepts Integer and AsyncOptions queueable delay values, duplicate signatures, and local AsyncOptions maximumQueueableStackDepth for Test.stopTest drain behavior."},
	{Area: "System", API: "System.enqueueJob hosted wall-clock queue scheduling", Status: StatusUnsupported, Notes: "Wall-clock queue scheduling and cross-transaction async locks require Salesforce async infrastructure."},
	{Area: "System", API: "System.runAs(Object,Object)", Status: StatusSupported, Notes: "Tracks local package-version test context during runAs execution."},
	{Area: "System", API: "System.runAs(Package.Version)", Status: StatusSupported, Notes: "Tracks local package-version test context during runAs execution."},
	{Area: "System", API: "System.runAs package install and license validation", Status: StatusUnsupported, Notes: "Package installation and license validation require hosted subscriber org state."},
	{Area: "System", API: "System.schedule(String,String,Object)", Status: StatusSupported, Notes: "Queues and drains local Scheduled Apex jobs during Test.stopTest with deterministic CronTrigger IDs."},
	{Area: "Test", API: "Test.enableChangeDataCapture()", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Test", API: "Test.getEventBus()", Status: StatusSupported, Notes: "Returns a local event-bus test broker that delivers queued platform-event triggers."},
	{Area: "Test", API: "Test.getExternalService()", Status: StatusSupported, Notes: "Returns a deterministic local external-service harness."},
	{Area: "Test", API: "Test.getExternalService live service execution", Status: StatusUnsupported, Notes: "External Service execution requires hosted named credential and generated service infrastructure."},
	{Area: "Test", API: "Test.invokeContinuationMethod(Object,Continuation)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Test", API: "Test.invokePage(PageReference)", Status: StatusSupported, Notes: "Returns a typed Component.apex.page handle in test context without rendering Visualforce."},
	{Area: "Test", API: "Test.newSendEmailQuickActionDefaults(Id,Id)", Status: StatusSupported, Notes: "Builds deterministic local send-email QuickAction defaults for test execution."},
	{Area: "Test", API: "Test.setContinuationResponse(String,HttpResponse)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Test", API: "Test.setCurrentPageReference(Object)", Status: StatusSupported, Notes: "Accepts PageReference object values and stores the VM-local current page."},
	{Area: "Test", API: "Test.testInstall(InstallHandler,Version)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Test", API: "Test.testInstall(InstallHandler,Version,Boolean)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Test", API: "Test.testNotificationActionHandler(Messaging.NotificationActionHandler,Messaging.ActionableNotification)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Test", API: "Test.testSandboxPostCopyScript(SandboxPostCopy,Id,Id,String)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Test", API: "Test.testSandboxPostCopyScript(SandboxPostCopy,Id,Id,String,Boolean)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "Test", API: "Test.testUninstall(UninstallHandler)", Status: StatusSupported, Notes: "Invokes the local test harness implementation."},
	{Area: "TrailblazerIdentity", API: "TrailblazerIdentity.generateUserEmailVerificationToken(String,String,String)", Status: StatusSupported, Notes: "Returns a deterministic local verification token for test execution."},
	{Area: "TrailblazerIdentity", API: "TrailblazerIdentity.getUserOrgInfo(List<String>)", Status: StatusSupported, Notes: "Returns an empty local UserOrgInfo list for deterministic test execution."},
	{Area: "TrailblazerIdentity", API: "TrailblazerIdentity.splunkLog(String,String)", Status: StatusSupported, Notes: "Accepts local log calls and returns null for deterministic test execution."},
	{Area: "UIRequest", API: "UIRequest.getCurrent()", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "UIRequest", API: "UIRequest.getRequestHeader(String)", Status: StatusSupported, Notes: "Returns deterministic local request context values for local Apex execution."},
	{Area: "UserInfo", API: "UserInfo.hasPackageLicense(Id)", Status: StatusSupported, Notes: "Checks local PackageLicense and UserPackageLicense records for the current runAs/default user."},
	{Area: "UserInfo", API: "UserInfo.isCurrentUserLicensedForPackage(Id)", Status: StatusSupported, Notes: "Checks local PackageLicense and UserPackageLicense records for the current runAs/default user."},
	{Area: "WebServiceCallout", API: "WebServiceCallout.invoke(Object,Object,Map,List)", Status: StatusSupported, Notes: "Validates SOAP options, routes generated SOAP callouts through registered WebServiceMock implementations, and materializes a deterministic local response shell when no mock is registered."},
	{Area: "WebServiceCallout", API: "WebServiceCallout.invoke(Object,Object,Map<String,Object>,List<String>)", Status: StatusSupported, Notes: "Validates SOAP options, routes generated SOAP callouts through registered WebServiceMock implementations, and materializes a deterministic local response shell when no mock is registered."},
	{Area: "WebServiceCallout", API: "WebServiceCallout outbound SOAP transport", Status: StatusUnsupported, Notes: "Real outbound SOAP transport requires external network service execution and is fenced locally."},
	{Area: "Pattern", API: "Matcher.find", Status: StatusSupported, Notes: "Oracle- and fixture-pinned regexp2-backed Java regex matching covers lookaround, named groups/backrefs, atomic groups, possessive quantifiers, \\G, \\R, \\h/\\v, (?U), Java Unicode aliases, UAX #29 \\X and \\b{g}, nested class algebra, and Apex UTF-16 code-unit match indexes."},
	{Area: "Pattern", API: "Matcher.group", Status: StatusSupported, Notes: "Returns fixture-pinned whole-match and capture groups, including unmatched optional groups, over the supported Java regex path with Apex UTF-16 code-unit group bounds."},
	{Area: "Pattern", API: "Matcher.matches", Status: StatusSupported, Notes: "Whole-region matching over the supported regexp2-backed Java regex path."},
	{Area: "Pattern", API: "Pattern.compile", Status: StatusSupported, Notes: "Compiles the supported regexp2-backed Java regex path: common flags, quote escapes, lookaround, named groups/backrefs, atomic groups, possessive quantifiers, \\G, \\R, \\h/\\v, (?U), Java Unicode aliases, UAX #29 \\X and \\b{g}, and nested class algebra."},
	{Area: "Pattern", API: "Pattern.matches", Status: StatusSupported, Notes: "Whole-string matching over the supported regexp2-backed Java regex path, including UAX #29 grapheme patterns."},
	{Area: "Schema", API: "Schema.describeSObjects(List<String>)", Status: StatusSupported, Notes: "Returns local metadata object names, labels, key prefixes, access booleans, fields, record types, and SObjectType tokens."},
	{Area: "Schema", API: "Schema.getGlobalDescribe()", Status: StatusSupported, Notes: "Returns a local describe map for loaded standard, custom, namespaced, and project objects."},
	{Area: "Schema", API: "Schema.describeDataCategoryGroups(List<String>)", Status: StatusSupported, Notes: "Returns deterministic local data category group describes from loaded org metadata and an empty typed list when absent."},
	{Area: "Schema", API: "Schema.describeDataCategoryGroupStructures(List<Schema.DataCategoryGroupSobjectTypePair>,Boolean)", Status: StatusSupported, Notes: "Returns deterministic local data category structures from loaded org metadata."},
	{Area: "Schema", API: "Hosted org describe and data category services", Status: StatusUnsupported, Notes: "Live full-org describe breadth, admin-computed permissions, and hosted data category service lookup require Salesforce org services."},
	{Area: "Schema", API: "DescribeFieldResult", Status: StatusSupported, Notes: "Returns local metadata-backed field labels, picklists, reference targets, and access, create, and update booleans."},
	{Area: "Schema", API: "DescribeSObjectResult", Status: StatusSupported, Notes: "Returns local object labels, key prefixes, query and search flags, fields, record types, and child relationships."},
	{Area: "Search", API: "Search.query / SOSL FIND", Status: StatusSupported, Notes: "Parses supported RETURNING clauses and returns deterministic rows from fixed search results or local org records."},
	{Area: "Search", API: "Search.query(String,AccessLevel)", Status: StatusSupported, Notes: "Uses deterministic local org SOSL with AccessLevel permission checks."},
	{Area: "Search", API: "Search.find", Status: StatusSupported, Notes: "Returns deterministic SearchResult DTOs from fixed search results or local org records."},
	{Area: "Search", API: "Search.find(String,AccessLevel)", Status: StatusSupported, Notes: "Uses deterministic local org search with AccessLevel permission checks."},
	{Area: "Search", API: "Search.suggest", Status: StatusSupported, Notes: "Returns deterministic local org suggestion DTOs from name-like fields."},
	{Area: "Search", API: "Search.suggest(String,String,Search.SuggestionOption)", Status: StatusSupported, Notes: "Returns deterministic local org suggestions and respects local limit options."},
	{Area: "Search", API: "Search.suggest(String,String,Search.SuggestionOption,AccessLevel)", Status: StatusSupported, Notes: "Returns deterministic local org suggestions with AccessLevel permission checks."},
	{Area: "SObject", API: "SObject.setOptions(Database.DMLOptions)", Status: StatusSupported, Notes: "Stores a cloned DMLOptions value on the local SObject for later DML option use."},
	{Area: "String", API: "String.contains", Status: StatusSupported, Notes: "UTF-8 string contains."},
	{Area: "String", API: "String.endsWith", Status: StatusSupported, Notes: "UTF-8 string suffix."},
	{Area: "String", API: "String.equalsIgnoreCase", Status: StatusSupported, Notes: "Unicode simple fold."},
	{Area: "String", API: "String.indexOf", Status: StatusSupported, Notes: "UTF-8 byte index behavior from Go strings."},
	{Area: "String", API: "String.isBlank", Status: StatusSupported, Notes: "Null and whitespace."},
	{Area: "String", API: "String.isNotBlank", Status: StatusSupported, Notes: "Null and whitespace."},
	{Area: "String", API: "String.join", Status: StatusSupported, Notes: "List values and separator."},
	{Area: "String", API: "String.lastIndexOf", Status: StatusSupported, Notes: "UTF-8 byte index behavior from Go strings."},
	{Area: "String", API: "String.length", Status: StatusSupported, Notes: "Counts Apex UTF-16 code units."},
	{Area: "String", API: "String.replace", Status: StatusSupported, Notes: "Literal replacement."},
	{Area: "String", API: "String.split", Status: StatusSupported, Notes: "regexp2-backed Java Pattern split covers limits, empty-pattern splits, zero-width and nullable delimiters, numeric backreference delimiters, \\Q...\\E quote escapes, UAX #29 graphemes, nested class algebra, and Apex UTF-16 code-unit boundaries."},
	{Area: "String", API: "String.startsWith", Status: StatusSupported, Notes: "UTF-8 string prefix."},
	{Area: "String", API: "String.substring", Status: StatusSupported, Notes: "Rune-indexed substring."},
	{Area: "String", API: "String.toLowerCase", Status: StatusSupported, Notes: "Go Unicode lowercasing."},
	{Area: "String", API: "String.toUpperCase", Status: StatusSupported, Notes: "Go Unicode uppercasing."},
	{Area: "String", API: "String.trim", Status: StatusSupported, Notes: "Unicode whitespace trim."},
	{Area: "String", API: "String.valueOf", Status: StatusSupported, Notes: "Local value string conversion."},
	{Area: "System", API: "System.assert", Status: StatusSupported, Notes: "Assertion failure returns runtime error."},
	{Area: "System", API: "System.assertEquals", Status: StatusSupported, Notes: "Assertion failure returns runtime error."},
	{Area: "System", API: "System.debug", Status: StatusSupported, Notes: "Collected in result debug output."},
	{Area: "Test", API: "Test.getStandardPricebookId", Status: StatusSupported, Notes: "Returns the deterministic local standard pricebook ID in test context."},
	{Area: "Test", API: "Test.createStubQueryRow", Status: StatusSupported, Notes: "Builds one local SObject row from a field map for SOQL stub providers."},
	{Area: "Test", API: "Test.createStubQueryRow(Schema.SObjectType,Map<String,Object>)", Status: StatusSupported, Notes: "Builds one local SObject row from a field map for SOQL stub providers."},
	{Area: "Test", API: "Test.createStubQueryRows", Status: StatusSupported, Notes: "Builds local SObject row lists from field maps for SOQL stub providers."},
	{Area: "Test", API: "Test.createStubQueryRows(Schema.SObjectType,List<Map<String,Object>>)", Status: StatusSupported, Notes: "Builds local SObject row lists from field maps for SOQL stub providers."},
	{Area: "Test", API: "Test.createSoqlStub(Schema.SObjectType,SoqlStubProvider)", Status: StatusSupported, Notes: "Registers test-local SOQL stubs per SObject type."},
	{Area: "Test", API: "Test.createStub(Type,StubProvider)", Status: StatusSupported, Notes: "Creates dynamic test stubs backed by StubProvider."},
	{Area: "Test", API: "Test.isRunningTest", Status: StatusSupported, Notes: "Reflects local test context."},
	{Area: "Test", API: "Test.loadData", Status: StatusSupported, Notes: "Loads CSV static-resource content with typed field coercion, DML routing, missing-resource errors, and bad-header diagnostics."},
	{Area: "Test", API: "Test.loadData packaged resource and relationship external-ID expansion", Status: StatusUnsupported, Notes: "Packaged static-resource namespace lookup and relationship external-ID fixture expansion require hosted packaging and schema behavior beyond local CSV loading."},
	{Area: "Test", API: "Test.setCurrentPage(PageReference)", Status: StatusSupported, Notes: "Sets the VM-local current PageReference in test context."},
	{Area: "Test", API: "Test.setCurrentPageReference(PageReference)", Status: StatusSupported, Notes: "Sets the VM-local current PageReference in test context."},
	{Area: "Test", API: "Test.setMock", Status: StatusSupported, Notes: "Registers HttpCalloutMock and WebServiceMock routes for local tests."},
	{Area: "Test", API: "Test.startTest", Status: StatusSupported, Notes: "Resets the active governor window for deterministic local counters."},
	{Area: "Test", API: "Test.stopTest", Status: StatusSupported, Notes: "Restores outer governor counters and drains supported local async work."},
	{Area: "Test", API: "Test.startTest and stopTest hosted service accounting", Status: StatusUnsupported, Notes: "Hosted async service execution and exact Salesforce governor accounting require Salesforce runtime services."},
	{Area: "Time", API: "Time.hour", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.minute", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.newInstance", Status: StatusSupported, Notes: "Validates time parts."},
	{Area: "Time", API: "Time.second", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.valueOf", Status: StatusSupported, Notes: "Parses supported time strings."},
	{Area: "TimeZone", API: "TimeZone.getDisplayName", Status: StatusSupported, Notes: "Returns deterministic display names for local timezone values."},
	{Area: "TimeZone", API: "TimeZone.getID", Status: StatusSupported, Notes: "Returns local timezone IDs."},
	{Area: "TimeZone", API: "TimeZone.getOffset", Status: StatusSupported, Notes: "Returns offsets from the deterministic local timezone model."},
	{Area: "TimeZone", API: "TimeZone.getTimeZone", Status: StatusSupported, Notes: "Resolves timezone IDs into local timezone values."},
	{Area: "Type", API: "Type.forName", Status: StatusSupported, Notes: "Resolves local classes, SObjects, built-ins, generic type names, generated platform types, and common platform namespace aliases."},
	{Area: "Type", API: "Type.forName hosted package namespace reflection", Status: StatusUnsupported, Notes: "Live package namespace reflection beyond local source and generated platform aliases requires hosted org metadata."},
	{Area: "Type", API: "Type.getName", Status: StatusSupported, Notes: "Returns local type token name."},
	{Area: "URL", API: "URL.getOrgDomainUrl", Status: StatusSupported, Notes: "Deterministic local org URL."},
	{Area: "URL", API: "URL.getSalesforceBaseUrl", Status: StatusSupported, Notes: "Deterministic local base URL."},
	{Area: "Unsupported", API: "unimplemented platform/stdlib calls", Status: StatusSupported, Notes: "Typed UnsupportedFeature errors with stable message text."},
	{Area: "UserInfo", API: "UserInfo.getLanguage", Status: StatusSupported, Notes: "Returns the current runAs/default user's local language value."},
	{Area: "UserInfo", API: "UserInfo.getLocale", Status: StatusSupported, Notes: "Returns the current runAs/default user's local locale value."},
	{Area: "UserInfo", API: "UserInfo.getFirstName", Status: StatusSupported, Notes: "Returns the current runAs/default user's local first name."},
	{Area: "UserInfo", API: "UserInfo.getLastName", Status: StatusSupported, Notes: "Returns the current runAs/default user's local last name."},
	{Area: "UserInfo", API: "UserInfo.getName", Status: StatusSupported, Notes: "Returns the current runAs/default user's local display name."},
	{Area: "UserInfo", API: "UserInfo.getOrganizationId", Status: StatusSupported, Notes: "Returns the deterministic local org identity."},
	{Area: "UserInfo", API: "UserInfo.getProfileId", Status: StatusSupported, Notes: "Returns the current runAs/default user's local profile id."},
	{Area: "UserInfo", API: "UserInfo.getSessionId", Status: StatusSupported, Notes: "Returns the deterministic empty local session value."},
	{Area: "UserInfo", API: "UserInfo.getTimeZone", Status: StatusSupported, Notes: "Returns the deterministic local user timezone."},
	{Area: "UserInfo", API: "UserInfo.getUserEmail", Status: StatusSupported, Notes: "Returns the current runAs/default user's local email value."},
	{Area: "UserInfo", API: "UserInfo.getUserId", Status: StatusSupported, Notes: "Returns the current runAs/default user's local user id."},
	{Area: "UserInfo", API: "UserInfo.getUserName", Status: StatusSupported, Notes: "Returns the current runAs/default user's local username."},
	{Area: "UserInfo", API: "UserInfo.getUserType", Status: StatusSupported, Notes: "Returns the current runAs/default user's local user type."},
	{Area: "UserInfo", API: "UserInfo.isMultiCurrencyOrganization", Status: StatusSupported, Notes: "Returns the local org multi-currency metadata flag."},
}
