package oracleprobe

func StdlibCases() []Case {
	return []Case{
		{ID: "decimal-round-default-positive-tie", Area: "Decimal", API: "Decimal.round", Mode: ModeAnonymous, Expression: "Decimal.valueOf('2.5').round()", ValueType: "Integer"},
		{ID: "decimal-round-default-negative-tie", Area: "Decimal", API: "Decimal.round", Mode: ModeAnonymous, Expression: "Decimal.valueOf('-2.5').round()", ValueType: "Integer"},
		{ID: "decimal-round-half-up-positive", Area: "Decimal", API: "Decimal.round", Mode: ModeAnonymous, Expression: "Decimal.valueOf('2.5').round(RoundingMode.HALF_UP)", ValueType: "Integer"},
		{ID: "decimal-round-half-even-down", Area: "Decimal", API: "Decimal.round", Mode: ModeAnonymous, Expression: "Decimal.valueOf('12.5').round(RoundingMode.HALF_EVEN)", ValueType: "Integer"},
		{ID: "decimal-round-half-even-up", Area: "Decimal", API: "Decimal.round", Mode: ModeAnonymous, Expression: "Decimal.valueOf('13.5').round(RoundingMode.HALF_EVEN)", ValueType: "Integer"},
		{ID: "decimal-setscale-large-positive-scale", Area: "Decimal", API: "Decimal.setScale", Mode: ModeAnonymous, Expression: "Decimal.valueOf('1.234567890123456789').setScale(18, RoundingMode.HALF_UP)", ValueType: "Decimal"},
		{ID: "decimal-setscale-negative-scale", Area: "Decimal", API: "Decimal.setScale", Mode: ModeAnonymous, Expression: "Decimal.valueOf('125').setScale(-1, RoundingMode.HALF_UP)", ValueType: "Decimal"},
		{ID: "decimal-setscale-unnecessary-success", Area: "Decimal", API: "Decimal.setScale", Mode: ModeAnonymous, Expression: "Decimal.valueOf('1.20').setScale(2, RoundingMode.UNNECESSARY)", ValueType: "Decimal"},
		{ID: "decimal-setscale-unnecessary-throws", Area: "Decimal", API: "Decimal.setScale", Mode: ModeAnonymous, Expression: "Decimal.valueOf('1.21').setScale(1, RoundingMode.UNNECESSARY)", ExpectThrow: true},

		{ID: "encoding-urlencode-utf8-space-plus", Area: "EncodingUtil", API: "EncodingUtil.urlEncode", Mode: ModeAnonymous, Expression: "EncodingUtil.urlEncode('A B+', 'UTF-8')", ValueType: "String"},
		{ID: "encoding-urldecode-utf8-space-plus", Area: "EncodingUtil", API: "EncodingUtil.urlDecode", Mode: ModeAnonymous, Expression: "EncodingUtil.urlDecode('A+B%2B%CE%A9', 'utf8')", ValueType: "String"},
		{ID: "encoding-urlencode-latin1-roundtrip", Area: "EncodingUtil", API: "EncodingUtil.urlEncode", Mode: ModeAnonymous, Expression: "EncodingUtil.urlEncode(EncodingUtil.urlDecode('caf%E9+trail', 'ISO-8859-1'), 'ISO-8859-1')", ValueType: "String"},
		{ID: "encoding-urldecode-latin1", Area: "EncodingUtil", API: "EncodingUtil.urlDecode", Mode: ModeAnonymous, Expression: "EncodingUtil.urlDecode('caf%E9+trail', 'latin1')", ValueType: "String"},
		{ID: "encoding-urlencode-ascii-unrepresentable", Area: "EncodingUtil", API: "EncodingUtil.urlEncode", Mode: ModeAnonymous, Expression: "EncodingUtil.urlEncode(EncodingUtil.urlDecode('caf%E9', 'ISO-8859-1'), 'US-ASCII')", ExpectThrow: true},
		{ID: "encoding-urlencode-utf16", Area: "EncodingUtil", API: "EncodingUtil.urlEncode", Mode: ModeAnonymous, Expression: "EncodingUtil.urlEncode('x', 'UTF-16')", ValueType: "String"},

		{ID: "crypto-digest-md5", Area: "Crypto", API: "Crypto.generateDigest", Mode: ModeAnonymous, Expression: "EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueOf('abc')))", ValueType: "String"},
		{ID: "crypto-digest-sha1", Area: "Crypto", API: "Crypto.generateDigest", Mode: ModeAnonymous, Expression: "EncodingUtil.convertToHex(Crypto.generateDigest('SHA1', Blob.valueOf('abc')))", ValueType: "String"},
		{ID: "crypto-digest-sha-1", Area: "Crypto", API: "Crypto.generateDigest", Mode: ModeAnonymous, Expression: "EncodingUtil.convertToHex(Crypto.generateDigest('SHA-1', Blob.valueOf('abc')))", ValueType: "String"},
		{ID: "crypto-digest-sha256", Area: "Crypto", API: "Crypto.generateDigest", Mode: ModeAnonymous, Expression: "EncodingUtil.convertToHex(Crypto.generateDigest('SHA256', Blob.valueOf('abc')))", ValueType: "String"},
		{ID: "crypto-digest-sha-256", Area: "Crypto", API: "Crypto.generateDigest", Mode: ModeAnonymous, Expression: "EncodingUtil.convertToHex(Crypto.generateDigest('SHA-256', Blob.valueOf('abc')))", ValueType: "String"},
		{ID: "crypto-digest-sha3-256", Area: "Crypto", API: "Crypto.generateDigest", Mode: ModeAnonymous, Expression: "EncodingUtil.convertToHex(Crypto.generateDigest('SHA3-256', Blob.valueOf('abc')))", ValueType: "String"},
		{ID: "crypto-digest-bad-name", Area: "Crypto", API: "Crypto.generateDigest", Mode: ModeAnonymous, Expression: "Crypto.generateDigest('SHA-999', Blob.valueOf('abc'))", ExpectThrow: true},

		{ID: "string-split-empty-pattern", Area: "String", API: "String.split", Mode: ModeAnonymous, Expression: "JSON.serialize('abc'.split(''))", ValueType: "String"},
		{ID: "string-split-zero-limit", Area: "String", API: "String.split", Mode: ModeAnonymous, Expression: "JSON.serialize('a,,b,'.split(','))", ValueType: "String"},
		{ID: "string-split-negative-limit", Area: "String", API: "String.split", Mode: ModeAnonymous, Expression: "JSON.serialize('a,,b,'.split(',', -1))", ValueType: "String"},
		{ID: "string-split-positive-limit", Area: "String", API: "String.split", Mode: ModeAnonymous, Expression: "JSON.serialize('a,,b,'.split(',', 2))", ValueType: "String"},
		{ID: "string-split-word-boundary", Area: "String", API: "String.split", Mode: ModeAnonymous, Expression: "JSON.serialize('ab cd'.split('\\\\b', -1))", ValueType: "String"},

		{ID: "pattern-matches-lookahead", Area: "Pattern", API: "Pattern.matches", Mode: ModeAnonymous, Expression: "Pattern.matches('(?!^[0-9]*$)(?!^[a-zA-Z]*$)^([!-~]{8,50})$', 'abc123!!')", ValueType: "Boolean"},
		{ID: "pattern-compile-lookbehind-find", Area: "Pattern", API: "Pattern.compile", Mode: ModeAnonymous, Expression: "Pattern.compile('(?<=a)b').matcher('ab').find()", ValueType: "Boolean"},
		{ID: "pattern-compile-named-group", Area: "Pattern", API: "Pattern.compile", Mode: ModeAnonymous, Expression: "Pattern.compile('(?<word>[A-Z]+)').matcher('ABC').groupCount()", ValueType: "Integer"},
		{ID: "pattern-compile-class-intersection", Area: "Pattern", API: "Pattern.compile", Mode: ModeAnonymous, Expression: "Pattern.compile('[a-z&&[^aeiou]]+').matcher('bcdf').matches()", ValueType: "Boolean"},
		{ID: "pattern-matches-full-string", Area: "Pattern", API: "Pattern.matches", Mode: ModeAnonymous, Expression: "Pattern.matches('[A-Z]+', 'ABC')", ValueType: "Boolean"},
		{ID: "matcher-find-zero-width", Area: "Pattern", API: "Matcher.find", Mode: ModeAnonymous, Expression: "Pattern.compile('^|$').matcher('abc').find()", ValueType: "Boolean"},
		{ID: "pattern-grapheme-crlf-span", Area: "Pattern", API: "Pattern.compile", Mode: ModeAnonymous, Statements: []string{"String gladeCRLF = String.fromCharArray(new List<Integer>{13, 10})", "Matcher gladeCRLFMatcher = Pattern.compile('\\\\X').matcher(gladeCRLF)", "Map<String,Object> gladeCRLFSpan = new Map<String,Object>()", "gladeCRLFSpan.put('found', gladeCRLFMatcher.find())", "gladeCRLFSpan.put('start', gladeCRLFMatcher.start())", "gladeCRLFSpan.put('end', gladeCRLFMatcher.end())", "gladeCRLFSpan.put('groupChars', gladeCRLFMatcher.group().getChars())"}, Expression: "JSON.serialize(gladeCRLFSpan)", ValueType: "String"},
		{ID: "pattern-grapheme-zwj-family-span", Area: "Pattern", API: "Pattern.compile", Mode: ModeAnonymous, Statements: []string{"String gladeFamily = String.fromCharArray(new List<Integer>{55357, 56424, 8205, 55357, 56425, 8205, 55357, 56423, 8205, 55357, 56422})", "Matcher gladeFamilyMatcher = Pattern.compile('\\\\X').matcher(gladeFamily)", "Map<String,Object> gladeFamilySpan = new Map<String,Object>()", "gladeFamilySpan.put('found', gladeFamilyMatcher.find())", "gladeFamilySpan.put('start', gladeFamilyMatcher.start())", "gladeFamilySpan.put('end', gladeFamilyMatcher.end())", "gladeFamilySpan.put('groupChars', gladeFamilyMatcher.group().getChars())"}, Expression: "JSON.serialize(gladeFamilySpan)", ValueType: "String"},
		{ID: "matcher-find-thumbs-up-skin-tone-span", Area: "Pattern", API: "Matcher.find", Mode: ModeAnonymous, Statements: []string{"String gladeThumbs = String.fromCharArray(new List<Integer>{55357, 56397, 55356, 57341})", "Matcher gladeThumbsMatcher = Pattern.compile('\\\\X').matcher(gladeThumbs + 'x')", "Map<String,Object> gladeThumbsSpan = new Map<String,Object>()", "gladeThumbsSpan.put('found', gladeThumbsMatcher.find())", "gladeThumbsSpan.put('start', gladeThumbsMatcher.start())", "gladeThumbsSpan.put('end', gladeThumbsMatcher.end())", "gladeThumbsSpan.put('groupChars', gladeThumbsMatcher.group().getChars())"}, Expression: "JSON.serialize(gladeThumbsSpan)", ValueType: "String"},
		{ID: "pattern-grapheme-boundary-spans", Area: "Pattern", API: "Pattern.compile", Mode: ModeAnonymous, Statements: []string{"String gladeBoundaryInput = 'A' + String.fromCharArray(new List<Integer>{55357, 56397, 55356, 57341}) + 'B'", "Matcher gladeBoundaryMatcher = Pattern.compile('\\\\b{g}').matcher(gladeBoundaryInput)", "List<String> gladeBoundarySpans = new List<String>()", "if (gladeBoundaryMatcher.find()) gladeBoundarySpans.add(String.valueOf(gladeBoundaryMatcher.start()) + ':' + String.valueOf(gladeBoundaryMatcher.end()))", "if (gladeBoundaryMatcher.find()) gladeBoundarySpans.add(String.valueOf(gladeBoundaryMatcher.start()) + ':' + String.valueOf(gladeBoundaryMatcher.end()))", "if (gladeBoundaryMatcher.find()) gladeBoundarySpans.add(String.valueOf(gladeBoundaryMatcher.start()) + ':' + String.valueOf(gladeBoundaryMatcher.end()))", "if (gladeBoundaryMatcher.find()) gladeBoundarySpans.add(String.valueOf(gladeBoundaryMatcher.start()) + ':' + String.valueOf(gladeBoundaryMatcher.end()))", "if (gladeBoundaryMatcher.find()) gladeBoundarySpans.add(String.valueOf(gladeBoundaryMatcher.start()) + ':' + String.valueOf(gladeBoundaryMatcher.end()))"}, Expression: "JSON.serialize(gladeBoundarySpans)", ValueType: "String"},
		{ID: "pattern-class-algebra-nested-intersection", Area: "Pattern", API: "Pattern.compile", Mode: ModeAnonymous, Expression: "JSON.serialize(new List<Boolean>{Pattern.matches('[a-z&&[b-d&&[^c]]]+', 'bd'), Pattern.matches('[a-z&&[b-d&&[^c]]]+', 'bc')})", ValueType: "String"},
		{ID: "pattern-class-algebra-nested-subtraction", Area: "Pattern", API: "Pattern.compile", Mode: ModeAnonymous, Expression: "JSON.serialize(new List<Boolean>{Pattern.matches('[a-z&&[^m-p]]+', 'abcxyz'), Pattern.matches('[a-z&&[^m-p]]+', 'mnop')})", ValueType: "String"},
		{ID: "matcher-group-optional-missing", Area: "Pattern", API: "Matcher.group", Mode: ModeAnonymous, Statements: []string{"Matcher gladeMatcher = Pattern.compile('([A-Z]+)([0-9]+)?').matcher('ABC')", "gladeMatcher.find()"}, Expression: "gladeMatcher.group(2)", ValueType: "String"},
		{ID: "matcher-matches-full-string", Area: "Pattern", API: "Matcher.matches", Mode: ModeAnonymous, Expression: "Pattern.compile('[A-Z]+').matcher('ABC').matches()", ValueType: "Boolean"},

		{ID: "string-fromchararray-utf16-surrogate-pair", Area: "String", API: "String.fromCharArray", Mode: ModeAnonymous, Statements: []string{"String gladeSurrogatePair = String.fromCharArray(new List<Integer>{55357, 56397})", "Map<String,Object> gladeSurrogatePairShape = new Map<String,Object>()", "gladeSurrogatePairShape.put('length', gladeSurrogatePair.length())", "gladeSurrogatePairShape.put('chars', gladeSurrogatePair.getChars())", "gladeSurrogatePairShape.put('codePointCount', gladeSurrogatePair.codePointCount(0, gladeSurrogatePair.length()))"}, Expression: "JSON.serialize(gladeSurrogatePairShape)", ValueType: "String"},
		{ID: "string-fromchararray-scalar-out-of-bmp", Area: "String", API: "String.fromCharArray", Mode: ModeAnonymous, Statements: []string{"String gladeScalar = String.fromCharArray(new List<Integer>{128077})", "Map<String,Object> gladeScalarShape = new Map<String,Object>()", "gladeScalarShape.put('length', gladeScalar.length())", "gladeScalarShape.put('chars', gladeScalar.getChars())", "gladeScalarShape.put('codePointAt0', gladeScalar.codePointAt(0))", "gladeScalarShape.put('codePointCount', gladeScalar.codePointCount(0, gladeScalar.length()))"}, Expression: "JSON.serialize(gladeScalarShape)", ValueType: "String"},
		{ID: "string-fromchararray-utf16-truncated-scalar", Area: "String", API: "String.fromCharArray", Mode: ModeAnonymous, Statements: []string{"String gladeTruncatedScalar = String.fromCharArray(new List<Integer>{65536, 65537, 1114111})", "Map<String,Object> gladeTruncatedScalarShape = new Map<String,Object>()", "gladeTruncatedScalarShape.put('length', gladeTruncatedScalar.length())", "gladeTruncatedScalarShape.put('chars', gladeTruncatedScalar.getChars())", "gladeTruncatedScalarShape.put('codePointCount', gladeTruncatedScalar.codePointCount(0, gladeTruncatedScalar.length()))"}, Expression: "JSON.serialize(gladeTruncatedScalarShape)", ValueType: "String"},

		{ID: "json-untyped-numeric-shapes", Area: "JSON", API: "JSON.deserializeUntyped", Mode: ModeAnonymous, Expression: "JSON.serialize(JSON.deserializeUntyped('{\"whole\":12,\"big\":9223372036854775808,\"ratio\":1.25}'))", ValueType: "String"},
		{ID: "json-untyped-duplicate-keys", Area: "JSON", API: "JSON.deserializeUntyped", Mode: ModeAnonymous, Expression: "JSON.serialize(JSON.deserializeUntyped('{\"Name\":\"First\",\"Name\":\"Second\"}'))", ValueType: "String"},
		{ID: "json-serialize-primitive-map", Area: "JSON", API: "JSON.serialize", Mode: ModeAnonymous, Expression: "JSON.serialize(new Map<String,Object>{'b'=>2,'a'=>1,'n'=>null})", ValueType: "String"},
		{ID: "json-serialize-pretty-map", Area: "JSON", API: "JSON.serializePretty", Mode: ModeAnonymous, Expression: "JSON.serializePretty(new Map<String,Object>{'b'=>2,'a'=>1,'n'=>null})", ValueType: "String"},
		{ID: "json-deserialize-string-key-map", Area: "JSON", API: "JSON.deserialize", Mode: ModeAnonymous, Expression: "JSON.serialize((Map<String,Integer>)JSON.deserialize('{\"a\":1,\"b\":null}', Map<String,Integer>.class))", ValueType: "String"},
		{ID: "json-deserialize-id-key-map", Area: "JSON", API: "JSON.deserialize", Mode: ModeAnonymous, Expression: "JSON.serialize((Map<Id,String>)JSON.deserialize('{\"001B000001DVM9t\":\"Acme\"}', Map<Id,String>.class))", ValueType: "String"},
		{ID: "json-strict-duplicate-fields", Area: "JSON", API: "JSON.deserializeStrict", Mode: ModeAnonymous, Expression: "JSON.deserializeStrict('{\"Name\":\"First\",\"Name\":\"Second\"}', Account.class)", ExpectThrow: true},
		{ID: "json-strict-unknown-sobject-field", Area: "JSON", API: "JSON.deserializeStrict", Mode: ModeAnonymous, Expression: "JSON.deserializeStrict('{\"Name\":\"Acme\",\"NoSuchField__c\":\"x\"}', Account.class)", ExpectThrow: true},
	}
}
